### ISSUE TITLE
missing code to build OutputLinear.o

### ISSUE THREAD

**Issue by p-code** [cnlohr/colorchord#1]
make stops with:

make: *** No rule to make target `OutputLinear.o', needed by `colorchord'.

**Comment by Penagwin** [comment]
Seem to get the same issue. Removing OutputLinear from the make file lets it compile, however there aren't any pretty colors visualizing the sound.

**Comment by cnlohr** [comment]
Just fixed that.  I forgot to include the .c file.  I also switched the default input from "whatever is playing from the computer" to the default sound input in  2d6bba92b7cbb91fe156148ed8e8da33ab0f49e3
