### ISSUE TITLE
I'm Noob need help

### ISSUE THREAD

**Issue by sahilm10** [cnlohr/colorchord#106]
Just saw your video on colorchord 2. I don't have any background in programming. I was wondering how it works, do you connect a mic and ws2812b to esp8266 ? and flash your code to it? Does colorchord works standalone on esp8266? Is that how it works? I very interested in your work please guide me how do I get started?

**Comment by cnlohr** [comment]
It does work stand-alone on an ESP8266...  You will need to learn how to flash firmware on an ESP, and get the environment set up elsewhere.  Check out esp-open-sdk by pfalcon.  Once you get it set up you can flash on the boot, main and web image.  Then it is a stand-alone colorchord box.

**Comment by sahilm10** [comment]
so I checked out esp-open-sdk by pfalcon installed it on ubuntu 20.04 got an error for python serial and bash 3.1. tried googling about it, didn't work, so I left this project and end up installing audio-reactive-led-strip by Scott Lawson, which was fine but wasn't satisfying. until I saw you made a video about installing esp82xx toolchain, which is all I needed since June, would have made my life so much easier, I mean windows subsystem for Linux I didn't know shit about that, I been VMing since June which crashes my pc all the time. at this point i don't even know why people use VMWARE for?
so now I followed your video installed the toolchain and tried compiling colorchord embeded8266 and esp8266ws2812i2s but it won't compile, tried git pull origin master in esp82xx folder doesn't works. shows this error 

#error "end of USER_DATA doesn't line up with MFS_PAGE_OFFSET from the makefile"
  ^
make: *** [esp82xx/main.mf:134: image.elf] Error 1

**Comment by sahilm10** [comment]
can you send me the precompiled bin files, why do we have to recompile all the all time anyway?
found this neat software which flashs bin file to nodemcu https://github.com/nodemcu/nodemcu-flasher

**Comment by cnlohr** [comment]
The reason is the binaries are large, and every time the code changes, they are kept in the git tree. The git repositories can't be made huge.

**Comment by cnlohr** [comment]
That said... I can't look into this right now, perhaps someone else will come by, but I will be returning to colorchord on the 8266 soon, at which time, I believe it is mature enough and I will commit the binaries.

**Comment by sahilm10** [comment]
okay, waiting for it, And I figure a way out to use colorchord by sending udp packets to esp8266, thank you.
