### ISSUE TITLE
Spelling Error in Config Option

### ISSUE THREAD

**Issue by CaiB** [cnlohr/colorchord#108]
The Cells output is looking for a `seady_bright` parameter [here](https://github.com/cnlohr/colorchord/blob/master/colorchord2/OutputCells.c#L202), whereas [Linear](https://github.com/cnlohr/colorchord/blob/master/colorchord2/OutputLinear.c#L207) looks for `steady_bright`.

Potentially config-breaking, so not sure if it's worth fixing?

**Comment by cnlohr** [comment]
Yes.  Please fix.
