### ISSUE TITLE
Application doesn't run in headless mode

### ISSUE THREAD

**Issue by HeMe2** [cnlohr/colorchord#110]
Hi, 
maybe I get the headless mode wrong, but I thought the application shall run in background without any GUI. 
In Commit [4a3d06397b810a2d51e50079992948ab2c5dd0c4](https://github.com/cnlohr/colorchord/commit/4a3d06397b810a2d51e50079992948ab2c5dd0c4) the condition of the main while loop was changed (line 423 in that time), so that the application will never run in headless mode. 

If I got the intention of headless mode wrong, please tell me what headless should do. Otherwise we may change the condition to something else. For me a `while(1)` works great, but maybe I'm missing some corner cases where you can't shutdown the application with an OS signal. 

cheers
Henning

**Comment by CaiB** [comment]
This was changed when Charles added support for Android, and seems like an easy fix.

**Comment by HeMe2** [comment]
Thank you for your fast reply. 
Yeah, I could see that from the commit history, what I don't know is: Does `while(1)` break anything, when not on Android?
And yes, the fix is pretty easy if we don't need to take care of any other conditions.

**Comment by CaiB** [comment]
I think it being `while(1)` on other platforms is fine, it appears that's what it was before, and at a glance I don't see any other problems it would cause. I'm just not 100% sure, so will wait for Charles' input.

**Comment by HeMe2** [comment]
I just tested the latest master (https://github.com/cnlohr/colorchord/commit/82d44ae6b58cac2d177fa430eb31aa2e5a75e71a) and now colorchord runs fine, with my headless configuration. So I close this Issue, since it is fixed.
