### ISSUE TITLE
unknown type name 'uint32_t' when compiling with the latest sdk

### ISSUE THREAD

**Issue by con-f-use** [cnlohr/colorchord#12]
Getting an `unknown type name 'uint32_t'` error, only when using the latest esp-open-sdk  (build with gcc 4.8.5 instead of 4.8.2). Here is the build log: http://paste.ubuntu.com/21643922/

The relevant part should be:

    /home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -mlongcalls -I/home/confus/usr/build/esp-open-sdk/sdk/include -Imyclib -Iinclude -Iuser -Os -I/home/confus/usr/build/esp-open-sdk/sdk/include/ -I../embeddedcommon -I. -Icommon -DICACHE_FLASH driver/uart.c common/mystuff.c common/flash_rewriter.c common/http.c common/http_custom.c common/mfs.c user/ws2812_i2s.c user/hpatimer.c user/custom_commands.c driver/adc.c ../embeddedcommon/DFT32.c ../embeddedcommon/embeddednf.c ../embeddedcommon/embeddedout.c user/user_main.c common/commonservices.c   -nostdlib -L/home/confus/usr/build/esp-open-sdk/sdk/lib -L/home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/libgcc.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libmain.a /home/confus/usr/build/esp-open-sdk/sdk/lib/liblwip.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libssl.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libupgrade.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libnet80211.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libwpa.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libnet80211.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libphy.a /home/confus/usr/build/esp-open-sdk/sdk/lib/liblwip.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libpp.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libcrypto.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libmain.a /home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/libgcc.a -T /home/confus/usr/build/esp-open-sdk/sdk/ld/eagle.app.v6.ld -Wl,-Map,output.map  -B/home/confus/usr/build/esp-open-sdk/sdk/lib -o image.elf
    In file included from driver/uart.c:15:0:
    /home/confus/usr/build/esp-open-sdk/sdk/include/ets_sys.h:14:1: error: unknown type name 'uint32_t'
     typedef uint32_t ETSSignal;
     ^

**Comment by cnlohr** [comment]
Try throwing in a #include <stdint.h> at the top of uart.c?

**Comment by pelrun** [comment]
That sounds like a problem with the build environment, not colorchord. Do you have the espressif sdk properly installed?

**Comment by con-f-use** [comment]
I believe I have. At least I can compile and flash [esp8266ws2812i2s](https://github.com/cnlohr/esp8266ws2812i2s) just fine. 

The file that defines fixed size integer types is `esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/include/stdint.h` as far as I know. Even if I include that in  `uart.c`, the type is not recognized.
Maybe there's just an include missing in the Makefile

**Comment by pelrun** [comment]
The error happens in /home/confus/usr/build/esp-open-sdk/sdk/include/ets_sys.h immediately after an #include "c_types.h", and *that* file (/home/confus/usr/build/esp-open-sdk/sdk/include/c_types.h) should be defining the type. Unless there's another c_types.h file that's getting loaded instead.

**Comment by con-f-use** [comment]
I looked a bit more into it. `c_types.h` seems to get patched at some point during building the compiler. If I replace the patched version with the original version, I get a much shorter linking error:

```
/home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -mlongcalls -I/home/confus/usr/build/esp-open-sdk/sdk/include -Imyclib -Iinclude -Iuser -Os -I/home/confus/usr/build/esp-open-sdk/sdk/include/ -I../embeddedcommon -I. -Icommon -DICACHE_FLASH driver/uart.c common/mystuff.c common/flash_rewriter.c common/http.c common/http_custom.c common/mfs.c user/ws2812_i2s.c user/hpatimer.c user/custom_commands.c driver/adc.c ../embeddedcommon/DFT32.c ../embeddedcommon/embeddednf.c ../embeddedcommon/embeddedout.c user/user_main.c common/commonservices.c   -nostdlib -L/home/confus/usr/build/esp-open-sdk/sdk/lib -L/home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/libgcc.a /home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/libgcc.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libmain.a /home/confus/usr/build/esp-open-sdk/sdk/lib/liblwip.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libssl.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libupgrade.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libnet80211.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libwpa.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libnet80211.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libphy.a /home/confus/usr/build/esp-open-sdk/sdk/lib/liblwip.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libpp.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libcrypto.a /home/confus/usr/build/esp-open-sdk/sdk/lib/libmain.a /home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/libgcc.a -T /home/confus/usr/build/esp-open-sdk/sdk/ld/eagle.app.v6.ld -Wl,-Map,output.map  -B/home/confus/usr/build/esp-open-sdk/sdk/lib -o image.elf
/home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: image.elf section `.text' will not fit in region `iram1_0_seg'
/home/confus/usr/build/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: region `iram1_0_seg' overflowed by 1912 bytes
collect2: error: ld returned 1 exit status
Makefile:83: recipe for target 'image.elf' failed
make: *** [image.elf] Error 1
```

**Comment by pelrun** [comment]
That's issue #10 - you cannot use the latest Espressif SDK, you need to use 1.5.1.

**Comment by con-f-use** [comment]
Okay, thank you. That is really annoying. Can you or someone else proved a commit of the [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) Makefile by [pfalcon](https://github.com/pfalcon) that doesn't have the error?

**Comment by cnlohr** [comment]
I actually just tried a couple things tonight and have found that after 1.5.1, Espressif really started to LOAD DOWN the iram segment with tons of stuff.  There's basically no room left.  Unfortunately, much of colorchord needs the iram to run, so unless Espressif makes some big changes we're stuck with 1.5.1. 

I am really confused about this needing to patch, etc.  P.S.  I need to backport it into colorchord, unless someone here is up for it, but I have updated it so everything uses esptool.py.  No more need to have the binary esptool.  Does anyone mind giving that a shot and testing?

**Comment by con-f-use** [comment]
> I need to backport it into colorchord

"It" being...? I'd be up for some testing but what exactly do you want to backport and test?

**Comment by cnlohr** [comment]
1) "it" = things like:
```
$(FW_FILES): $(TARGET_OUT)
	@echo "FW $@"
	PATH=$(FOLDERPREFIX):$$PATH;$(ESPTOOL_PY) elf2image $(TARGET_OUT)
```
So we don't need the binary.

and 
```
burn : $(FW_FILES)
	$(ESPTOOL_PY) --port $(PORT) write_flash -fm dout 0x00000 image.elf-0x00000.bin 0x40000 image.elf-0x40000.bin
```
so it doesn't confuse the baud rate detector.

2) I am definitely using Mint 17.3 and it has built everything cleanly.  Not sure what the difference is there.

The defaults are for it to make its own AP, you connect, it is at 192.168.4.1.  You can use the web configuration to connect to another AP.

**Comment by con-f-use** [comment]
see pull request #13 

I'm thinking of rewriting ./embedded8266/web/Makefile so that it can be included in the main Makefile and things like `page.mpfs` and `execute_reflash` are build automatically on demand from the main Makefile.

**Comment by cnlohr** [comment]
You may want to consider writing the rule in the main like so:

```
do_web_stuff:
	(cd web)&&(make);(cd ..)

**Comment by cnlohr** [comment]
P.S. @con-f-use  I really appreciate you helping out on this!

**Comment by con-f-use** [comment]
> You may want to consider writing the rule in the main

And so t'was done ---> #14
