### ISSUE TITLE
CFNA Drivers Not Found

### ISSUE THREAD

**Issue by ShiromMakkad** [cnlohr/colorchord#121]
I'm compiling colorchord2 on Windows with clang. I've got the Windows sdk installed, but when I run Colorchord, I get an error about the CFNA Drivers not being found and the GUI says that sound isn't available. How can I fix this?

**Comment by sellicott** [comment]
Hello, thanks for reporting this.
This was a CNFA issue that was recently fixed. Apparently I never bumped the submodule in colorchord to reflect the changes. It should work now.

Update the submodule by running
```
git pull
git submodule update
```
Then compile normally (`.\compile-clang.bat`)
If this doesn't work, please let me know.
Thanks,
-Sam Ellicott
Soli Deo Gloria
