### ISSUE TITLE
Issue locationg USB Port for Embedded esp8266

### ISSUE THREAD

**Issue by tjd195** [cnlohr/colorchord#129]
I am using this: https://www.adafruit.com/product/2821

When I run usb-devices, I get :
T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 1
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.80-v7+ dwc_otg_hcd
S:  Product=DWC OTG Controller
S:  SerialNumber=3f980000.usb
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 4
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=02 MxPS=64 #Cfgs=  1
P:  Vendor=0424 ProdID=2514 Rev=0b.b3
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=2mA
I:  If#= 0 Alt= 1 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=02 Driver=hub

T:  Bus=01 Lev=02 Prnt=02 Port=00 Cnt=01 Dev#=  3 Spd=480 MxCh= 3
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=02 MxPS=64 #Cfgs=  1
P:  Vendor=0424 ProdID=2514 Rev=0b.b3
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=2mA
I:  If#= 0 Alt= 1 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=02 Driver=hub

T:  Bus=01 Lev=03 Prnt=03 Port=00 Cnt=01 Dev#=  6 Spd=480 MxCh= 0
D:  Ver= 2.10 Cls=ff(vend.) Sub=00 Prot=ff MxPS=64 #Cfgs=  1
P:  Vendor=0424 ProdID=7800 Rev=03.00
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=2mA
I:  If#= 0 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=ff Driver=lan78xx

T:  Bus=01 Lev=03 Prnt=03 Port=01 Cnt=02 Dev#=  5 Spd=1.5 MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=046d ProdID=c077 Rev=72.00
S:  Manufacturer=Logitech
S:  Product=USB Optical Mouse
C:  #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=100mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid

T:  Bus=01 Lev=02 Prnt=02 Port=02 Cnt=02 Dev#=  4 Spd=1.5 MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=046d ProdID=c31c Rev=64.00
S:  Manufacturer=Logitech
S:  Product=USB Keyboard
C:  #Ifs= 2 Cfg#= 1 Atr=a0 MxPwr=90mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=01 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

So it seems to be on PORT 00 to me, but when i run:
PORT=/dev/ttyUSB0 make erase
or
PORT=0 make erase

I get this error code:
esp82xx/common.mf:40: Warning: No shell variable 'ESP_ROOT', using '/home/pi/esp8266/esp-open-sdk'
/home/pi/esp8266/esp-open-sdk/esptool/esptool.py  --port /dev/ttyUSB0     erase_flash
esptool.py v1.2
Traceback (most recent call last):
  File "/home/pi/esp8266/esp-open-sdk/esptool/esptool.py", line 1270, in <module>
    main()
  File "/home/pi/esp8266/esp-open-sdk/esptool/esptool.py", line 1179, in main
    esp = ESPROM(args.port, initial_baud)
  File "/home/pi/esp8266/esp-open-sdk/esptool/esptool.py", line 71, in _init_
    self._port = serial.serial_for_url(port)
  File "/home/pi/.local/lib/python2.7/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/home/pi/.local/lib/python2.7/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
esp82xx/main.mf:215: recipe for target 'erase' failed
make: * [erase] Error 1

Anyone know what I am doing wrong?

**Comment by sellicott** [comment]
I'm assuming you are following the guide [here](https://github.com/cnlohr/colorchord/blob/master/embedded8266/README.md#build-instructions)

As you diagnosed, esptool cannot find your serial port. It is possible that your computer labeled the serial port something other than ttyUSB0 (ttyACM0 is also pretty common). To double check, try running disconnecting and reconnecting the esp8266 from the computer then run `sudo dmesg`

You should get a message something like this:
```
[10755.957780] usbcore: registered new interface driver ch341
[10755.957786] usbserial: USB Serial support registered for ch341-uart
[10755.957793] ch341 3-3:1.0: ch341-uart converter detected
[10755.969210] ch341-uart ttyUSB0: break control not supported, using simulated break
[10755.969250] usb 3-3: ch341-uart converter now attached to ttyUSB0
```

You can also try running `ls /dev/tty*` which will show you all the TTY ports you have available to you.
Hope this helps,
-Sam Ellicott
Soli Deo Gloria

**Comment by tjd195** [comment]
@sellicott 
I ran ls /dev/tty* and apparently there are like 63 or so tty ports. None are ttyACM0, but one is named ttyAMA0. 

when I ran sudo dmesg I get a whole lot of information printed to screen. Like exponentially more than you showed.

**Comment by tjd195** [comment]
after disconnect and reconnect I ran sudo dmesg | grep tty and get this:

[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1184 bcm2708_fb.fbheight=624 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p7 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait splash plymouth.ignore-serial-consoles
[    0.001206] console [tty1] enabled
[    0.994287] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2

So I am guessing it is at tty1?
Do I need to change the line of code in esptool.py to access it?

**Comment by sellicott** [comment]
I think tty1 is going to be an OS serial console and from some searching it seems like ttyAMA0 is a raspberry pi serial device that controls either the rx/tx lines or the bluetooth module (https://raspberrypi.stackexchange.com/questions/69697/what-is-dev-ttyama0).

Could you post some more of the unfiltered dmesg output for me to look at?

You were correct in your original post about setting the tty port
use `PORT=/dev/<tty_name> make erase` to use a particular port.

**Comment by sellicott** [comment]
Another thing to try is to run `lsusb` this will show the usb devices attached (unfortunately no tty names though). Try running with the esp connected and disconnected to see if anything changes.

**Comment by tjd195** [comment]
there were no changes when running lsusb :-(

But here is the unfiltered dmesg:
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.9.80-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1098 SMP Fri Mar 9 19:11:42 GMT 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt:Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c6f800, node_mem_map ba3a1000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 14 pages/cpu @ba35b000 s25600 r8192 d23552 u57344
[    0.000000] pcpu-alloc: s25600 r8192 d23552 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1184 bcm2708_fb.fbheight=624 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p7 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940364K/970752K available (7168K kernel code, 487K rwdata, 2032K rodata, 1024K init, 770K bss, 22196K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c79cbc   ( 488 kB)
                      .bss : 0x80c7b000 - 0x80d3b9e4   ( 771 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] arm_arch_timer: Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000006] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000022] Switching to timer-based delay loop, resolution 52ns
[    0.000298] Console: colour dummy device 80x30
[    0.001206] console [tty1] enabled
[    0.001250] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001316] pid_max: default: 32768 minimum: 301
[    0.001652] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001694] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002729] Disabling memory control group subsystem
[    0.002832] CPU: Testing write buffer coherency: ok
[    0.002895] ftrace: allocating 22627 entries in 67 pages
[    0.050571] CPU0: update cpu_capacity 1024
[    0.050622] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.050681] Setting up static identity map for 0x100000 - 0x100034
[    0.052535] CPU1: update cpu_capacity 1024
[    0.052542] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.053187] CPU2: update cpu_capacity 1024
[    0.053194] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.053820] CPU3: update cpu_capacity 1024
[    0.053826] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.053914] Brought up 4 CPUs
[    0.054087] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.054117] CPU: All CPU(s) started in HYP mode.
[    0.054143] CPU: Virtualization extensions available.
[    0.054964] devtmpfs: initialized
[    0.066296] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.066619] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.066680] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.067239] pinctrl core: initialized pinctrl subsystem
[    0.068174] NET: Registered protocol family 16
[    0.070504] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.079397] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.079445] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.079616] Serial: AMBA PL011 UART driver
[    0.081520] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.082067] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.151440] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb80d000, dmachans=0x1
[    0.153297] SCSI subsystem initialized
[    0.153618] usbcore: registered new interface driver usbfs
[    0.153728] usbcore: registered new interface driver hub
[    0.153844] usbcore: registered new device driver usb
[    0.160370] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-03-13 18:45
[    0.161857] clocksource: Switched to clocksource arch_sys_counter
[    0.209405] VFS: Disk quotas dquot_6.6.0
[    0.209517] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.209745] FS-Cache: Loaded
[    0.210011] CacheFiles: Loaded
[    0.222164] NET: Registered protocol family 2
[    0.223052] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.223189] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.223399] TCP: Hash tables configured (established 8192 bind 8192)
[    0.223512] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.223579] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.223811] NET: Registered protocol family 1
[    0.224246] RPC: Registered named UNIX socket transport module.
[    0.224278] RPC: Registered udp transport module.
[    0.224306] RPC: Registered tcp transport module.
[    0.224333] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.225375] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.227694] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.243749] FS-Cache: Netfs 'nfs' registered for caching
[    0.244747] NFS: Registering the id_resolver key type
[    0.244800] Key type id_resolver registered
[    0.244828] Key type id_legacy registered
[    0.247256] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.247403] io scheduler noop registered
[    0.247434] io scheduler deadline registered (default)
[    0.247737] io scheduler cfq registered
[    0.252901] BCM2708FB: allocated DMA memory fad00000
[    0.252965] BCM2708FB: allocated DMA channel 0 @ bb80d000
[    0.274196] Console: switching to colour frame buffer device 148x39
[    0.287592] bcm2835-rng 3f104000.rng: hwrng registered
[    0.287846] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.288576] vc-sm: Videocore shared memory driver
[    0.303588] brd: module loaded
[    0.316520] loop: module loaded
[    0.320446] Loading iSCSI transport class v2.0-870.
[    0.325106] libphy: Fixed MDIO Bus: probed
[    0.329151] usbcore: registered new interface driver lan78xx
[    0.333280] usbcore: registered new interface driver smsc95xx
[    0.337151] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.569040] Core Release: 2.80a
[    0.572856] Setting default values for core params
[    0.576683] Finished setting default values for core params
[    0.780885] Using Buffer DMA mode
[    0.784644] Periodic Transfer Interrupt Enhancement - disabled
[    0.788449] Multiprocessor Interrupt Enhancement - disabled
[    0.792312] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.796238] Dedicated Tx FIFOs mode
[    0.800474] WARN::dwc_otg_hcd_init:1032: FIQ DMA bounce buffers: virt = 0xbad14000 dma = 0xfad14000 len=9024
[    0.804606] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.824077] dwc_otg: Microframe scheduler enabled
[    0.824129] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x8059b380
[    0.828112] WARN::hcd_init_fiq:460: FIQ ASM at 0x8059b6f0 length 36
[    0.832022] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbb878000
[    0.835883] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.839733] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.843700] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.847657] Init: Port Power? op_state=1
[    0.851535] Init: Power Port (0)
[    0.855603] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.859584] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.863559] usb usb1: Product: DWC OTG Controller
[    0.867407] usb usb1: Manufacturer: Linux 4.9.80-v7+ dwc_otg_hcd
[    0.871199] usb usb1: SerialNumber: 3f980000.usb
[    0.875805] hub 1-0:1.0: USB hub found
[    0.879637] hub 1-0:1.0: 1 port detected
[    0.884096] dwc_otg: FIQ enabled
[    0.884101] dwc_otg: NAK holdoff enabled
[    0.884105] dwc_otg: FIQ split-transaction FSM enabled
[    0.884118] Module dwc_common_port init
[    0.884353] usbcore: registered new interface driver usb-storage
[    0.888429] mousedev: PS/2 mouse device common for all mice
[    0.893276] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.897520] bcm2835-cpufreq: min=600000 max=1400000
[    0.901870] sdhci: Secure Digital Host Controller Interface driver
[    0.905826] sdhci: Copyright(c) Pierre Ossman
[    0.910044] sdhost-bcm2835 3f202000.sdhost: could not get clk, deferring probe
[    0.916292] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.920442] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.925967] ledtrig-cpu: registered to indicate activity on CPUs
[    0.930209] hidraw: raw HID events driver (C) Jiri Kosina
[    0.934557] usbcore: registered new interface driver usbhid
[    0.938649] usbhid: USB HID core driver
[    0.943455] vchiq: vchiq_init_state: slot_zero = 0xbad80000, is_master = 0
[    0.948792] [vc_sm_connected_init]: start
[    0.957786] [vc_sm_connected_init]: end - returning 0
[    0.962139] Initializing XFRM netlink socket
[    0.966134] NET: Registered protocol family 17
[    0.970180] Key type dns_resolver registered
[    0.974573] Registering SWP/SWPB emulation handler
[    0.979248] registered taskstats version 1
[    0.990151] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.994287] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    1.000021] sdhost: log_buf @ bad13000 (fad13000)
[    1.081889] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    1.088222] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    1.092457] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    1.101966] Indeed it is in host mode hprt0 = 00021501
[    1.171979] of_cfs_init
[    1.176216] of_cfs_init: OK
[    1.183863] Waiting for root device /dev/mmcblk0p7...
[    1.191744] random: fast init done
[    1.201338] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    1.207011] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.212575] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.219260] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.234327] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.241957] mmc0: new high speed SDHC card at address aaaa
[    1.246464] mmcblk0: mmc0:aaaa SL16G 14.8 GiB
[    1.257824]  mmcblk0: p1 p2 < p5 p6 p7 >
[    1.300337] mmc1: new high speed SDIO card at address 0001
[    1.301902] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.302035] Indeed it is in host mode hprt0 = 00001101
[    1.326889] EXT4-fs (mmcblk0p7): mounted filesystem with ordered data mode. Opts: (null)
[    1.330806] VFS: Mounted root (ext4 filesystem) readonly on device 179:7.
[    1.345262] devtmpfs: mounted
[    1.363804] Freeing unused kernel memory: 1024K
[    1.532192] usb 1-1: New USB device found, idVendor=0424, idProduct=2514
[    1.536100] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.540875] hub 1-1:1.0: USB hub found
[    1.544933] hub 1-1:1.0: 4 ports detected
[    1.752376] systemd[1]: System time before build time, advancing clock.
[    1.861949] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.871932] NET: Registered protocol family 10
[    1.889087] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.925513] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.934853] systemd[1]: Detected architecture arm.
[    1.966880] systemd[1]: Set hostname to <raspberrypi>.
[    1.992249] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514
[    1.997033] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.003463] hub 1-1.1:1.0: USB hub found
[    2.009787] hub 1-1.1:1.0: 3 ports detected
[    2.121926] usb 1-1.3: new low-speed USB device number 4 using dwc_otg
[    2.279923] usb 1-1.3: New USB device found, idVendor=046d, idProduct=c31c
[    2.284600] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.289262] usb 1-1.3: Product: USB Keyboard
[    2.293865] usb 1-1.3: Manufacturer: Logitech
[    2.316542] input: Logitech USB Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:046D:C31C.0001/input/input0
[    2.361947] usb 1-1.1.2: new low-speed USB device number 5 using dwc_otg
[    2.382950] hid-generic 0003:046D:C31C.0001: input,hidraw0: USB HID v1.10 Keyboard [Logitech USB Keyboard] on usb-3f980000.usb-1.3/input0
[    2.416649] input: Logitech USB Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:046D:C31C.0002/input/input1
[    2.420313] systemd[1]: Listening on Syslog Socket.
[    2.433341] systemd[1]: Reached target Swap.
[    2.444417] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    2.455789] systemd[1]: Listening on udev Control Socket.
[    2.467697] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.480126] systemd[1]: Created slice User and Session Slice.
[    2.492199] hid-generic 0003:046D:C31C.0002: input,hidraw1: USB HID v1.10 Device [Logitech USB Keyboard] on usb-3f980000.usb-1.3/input1
[    2.492215] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.507904] usb 1-1.1.2: New USB device found, idVendor=046d, idProduct=c077
[    2.507913] usb 1-1.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.507920] usb 1-1.1.2: Product: USB Optical Mouse
[    2.507926] usb 1-1.1.2: Manufacturer: Logitech
[    2.512097] input: Logitech USB Optical Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/0003:046D:C077.0003/input/input2
[    2.521513] hid-generic 0003:046D:C077.0003: input,hidraw2: USB HID v1.11 Mouse [Logitech USB Optical Mouse] on usb-3f980000.usb-1.1.2/input0
[    2.691611] i2c /dev entries driver
[    2.821955] usb 1-1.1.1: new high-speed USB device number 6 using dwc_otg
[    2.952585] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800
[    2.952602] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.022263] EXT4-fs (mmcblk0p7): re-mounted. Opts: (null)
[    3.148772] systemd-journald[118]: Received request to flush runtime journal from PID 1
[    3.242248] libphy: lan78xx-mdiobus: probed
[    3.813759] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    4.108357] brcmfmac: F1 signature read @0x18000000=0x15264345
[    4.118790] usbcore: registered new interface driver brcmfmac
[    4.492951] brcmfmac: Firmware version = wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    4.493511] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 9.10.105 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2018-03-09 18:56:28 
[    4.530992] random: crng init done
[    5.469213] uart-pl011 3f201000.serial: no DMA platform data
[    6.000837] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    6.000928] brcmfmac: power management disabled
[    6.640371] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    6.719626] Adding 102396k swap on /var/swap.  Priority:-1 extents:1 across:102396k SSFS
[   10.069077] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   11.188994] fuse init (API version 7.26)
[   11.750332] Bluetooth: Core ver 2.22
[   11.750418] NET: Registered protocol family 31
[   11.750422] Bluetooth: HCI device and connection manager initialized
[   11.750436] Bluetooth: HCI socket layer initialized
[   11.750444] Bluetooth: L2CAP socket layer initialized
[   11.750460] Bluetooth: SCO socket layer initialized
[   11.770826] Bluetooth: HCI UART driver ver 2.3
[   11.770835] Bluetooth: HCI UART protocol H4 registered
[   11.770838] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   11.770932] Bluetooth: HCI UART protocol Broadcom registered
[   12.162931] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.162937] Bluetooth: BNEP filters: protocol multicast
[   12.162949] Bluetooth: BNEP socket layer initialized
[   12.260877] Bluetooth: RFCOMM TTY layer initialized
[   12.260892] Bluetooth: RFCOMM socket layer initialized
[   12.260912] Bluetooth: RFCOMM ver 1.11
[   14.099390] EXT4-fs (mmcblk0p5): mounted filesystem with ordered data mode. Opts: (null)

**Comment by tjd195** [comment]
Not insulted in any way. I haven't worked on anything like this before really. Will a usb cord from a phone not work? It usually can do both data and power.

**Comment by tjd195** [comment]
I changed the cord and it is working now. Thanks a ton
