### ISSUE TITLE
./pushtodev doesn't properly transfer the site (and netburn doesn't work either)

### ISSUE THREAD

**Issue by con-f-use** [cnlohr/colorchord#15]
I noticed that when I run:

```
./pushtodev 192.168.4.1      65536      page.mpfs
```

The page doesn't properly transfer with things missing and javascript errors. There seems to be some corruption, when writing to flash. I can't burn firmware over network either. Not by using the GUI nor by using the terminal programs. What's wrong here?

![pushtodev-error](http://i.imgur.com/qxvXnF0.png)

**Comment by cnlohr** [comment]
Wat??? I have never seen anything like that!  Can you show the output of pushtodev?

**Comment by con-f-use** [comment]
Sure, see the [lengthy make output](http://paste.ubuntu.com/22303005/) of all steps I took. Here is the shortened version:

```
$ make purge
$ make burn
$ make burnweb
$ cd web
$ make clean
$ make push
[...]
./pushtodev 192.168.4.1      65536      page.mpfs
Erase: 1
bufferout: 65536 1024 FW65536	1024	
bufferout: 66560 1024 FW66560	1024	# folded after this line
bufferout: 67584 1024 FW67584	1024	bufferout: 68608 1024 FW68608	1024	bufferout: 69632 1024 FW69632	1024	bufferout: 70656 1024 FW70656	1024	bufferout: 71680 1024 FW71680	1024	bufferout: 72704 1024 FW72704	1024	bufferout: 73728 1024 FW73728	1024	bufferout: 74752 1024 FW74752	1024	bufferout: 75776 1024 FW75776	1024	bufferout: 76800 1024 FW76800	1024	bufferout: 77824 1024 FW77824	1024	bufferout: 78848 1024 FW78848	1024	bufferout: 79872 1024 FW79872	1024	bufferout: 80896 1024 FW80896	1024	bufferout: 81920 1024 FW81920	1024	bufferout: 82944 1024 FW82944	1024	bufferout: 83968 1024 FW83968	1024	bufferout: 84992 1024 FW84992	1024	bufferout: 86016 1024 FW86016	1024	bufferout: 87040 1024 FW87040	1024	bufferout: 88064 1024 FW88064	1024	bufferout: 89088 1024 FW89088	1024	bufferout: 90112 1024 FW90112	1024	bufferout: 91136 1024 FW91136	1024	bufferout: 92160 1024 FW92160	1024	bufferout: 93184 1024 FW93184	1024	bufferout: 94208 1024 FW94208	1024	bufferout: 95232 1024 FW95232	1024	bufferout: 96256 1024 FW96256	1024	bufferout: 97280 1024 FW97280	1024	bufferout: 98304 1024 FW98304	1024	bufferout: 99328 1024 FW99328	1024	bufferout: 100352 1024 FW100352	1024	bufferout: 101376 1024 FW101376	1024	bufferout: 102400 1024 FW102400	1024	bufferout: 103424 1024 FW103424	1024	bufferout: 104448 1024 FW104448	1024	bufferout: 105472 1024 FW105472	1024	bufferout: 106496 1024 FW106496	1024	bufferout: 107520 1024 FW107520	1024	bufferout: 108544 1024 FW108544	1024	bufferout: 109568 1024 FW109568	1024	bufferout: 110592 1024 FW110592	1024	bufferout: 111616 1024 FW111616	1024	bufferout: 112640 1024 FW112640	1024	bufferout: 113664 1024 FW113664	1024	bufferout: 114688 1024 FW114688	1024	bufferout: 115712 1024 FW115712	1024	bufferout: 116736 1024 FW116736	1024	bufferout: 117760 1024 FW117760	1024	bufferout: 118784 1024 FW118784	1024	bufferout: 119808 1024 FW119808	1024	bufferout: 120832 1024 FW120832	1024	bufferout: 121856 1024 FW121856	1024	bufferout: 122880 1024 FW122880	1024	bufferout: 123904 1024 FW123904	1024	bufferout: 124928 1024 FW124928	1024	bufferout: 125952 1024 FW125952	1024	bufferout: 126976 1024 FW126976	1024	bufferout: 128000 1024 FW128000	1024	bufferout: 129024 1024 FW129024	1024	
bufferout: 130048 1024 FW130048	1024	
Erase: 2
bufferout: 131072 1024 FW131072	1024	
bufferout: 132096 1024 FW132096	1024	
bufferout: 133120 1024 FW133120	1024	
bufferout: 134144 1024 FW134144	1024	
bufferout: 135168 1024 FW135168	1024	
bufferout: 136192 0 FW136192	0
```

**Comment by cnlohr** [comment]
That's not possible as pushtodev verifies that the ESP got all of the blocks, if not, it retries.  I have been able to push even over things like espthernet which drops packets periodically without issue.

Perhaps somewhere on the writing end?

One other thing you should try: Bump the MPFS back up to the 1M boundary, where it naturally lives, since there's tons of space up there.  You can do this by using 1048576 instead of 65536

**Comment by con-f-use** [comment]
Doesn't work with 1048576, but I found this in the UART output:

```
MFS Not found at regular address (000003e9).
MFS Not found at alternative address (0000000000000000).
MFS Found at: 00000000
404(index.html)
```

**Comment by cnlohr** [comment]
Woah.  that is seriously weird.  I wrote the whole pushtodev thing a year ago and haven't ever needed to change it.

Also, I am going to be using the same command structure for my USB bootloader, so I do want to maintain the command-style used in issue_command even if the code structure changes.

Would you mind throwing some printf(...) debugging into the 'F' root command in issue_command.  It's where all the flash commands live.  What ESP SDK are you using?

**Comment by con-f-use** [comment]
> Would you mind throwing some printf(...) debugging into the 'F' root command in issue_command. It's where all the flash commands live. What ESP SDK are you using?

I'll try to get on it this week. I'm using

> ESP8266_NONOS_SDK Release Note
> esp_iot_sdk_v1.5.0_15_11_27

**Comment by cnlohr** [comment]
I've just tried several different things to get it to fail and I just can't seem to make it fail.  Does this happen on all ESP modules?  Perhaps something is wrong with that particular one?

**Comment by con-f-use** [comment]
I only have ESP-01 modules, and at least three have the problem.

**Comment by cnlohr** [comment]
If ESP-01, keep them at the 65536 address. 

If you are up for testing some things at a lower level, you can connect to the chip and send FR commands via UDP port 7878.

```
echo -ne "FR\t65536\t1024" | nc 192.168.4.1 7878 | hexdump -C
```

And print the output.

P.S. I strongly recommend getting an ESP-12E/F (or NodeMCU) board.  They are much more convenient pinouts.

Again, I really appreciate your input, I hope this doesn't sour your attitude too much.  It is very helpful to have someone make this stuff so much better.

**Comment by con-f-use** [comment]
I don't get any output with `echo -ne "FR\t65536\t1024" | nc 192.168.4.1 7878 | hexdump -C`. If I type it into the custom command field in the WebUI, I get the response `!FR` so no data at all.

**Comment by cnlohr** [comment]
Oh no!  What I sent was a Linux terminal command.   I don't know if Mac has those tools, I just know it on Linux.  

There is no way to test the issue with the web gui as the web gui would be broken when we want to test - so - the only way to do it is using netcat or something else that can send raw USB packets.

Here is a copy of my page.mpfs.  

[page.mpfs.zip](https://github.com/cnlohr/colorchord/files/409148/page.mpfs.zip)

Can't send the firmware right now.  Maybe later today.  I still think testing the Linux terminal command to send the read command will be the best test!

**Comment by con-f-use** [comment]
Using the Web-GUI was just an additional thing, I tried. I DID use your terminal command and got no reply. Btw. I really appreciate your help an patience here :-)

**Comment by cnlohr** [comment]
I'm so sorry... it's ```nc [ip] 7878 -u -w 1``` need to specify uDP and wAIT :-/ I don't know how I missed that every time.  I didn't see it till you c&p'd what you had.

Specifically, I modified the mfs system for someone who wanted to get it working on the 512kB flash, so it "should" work as long as you're writing to 65536 not 1048576 -- if you are operating with the 12E, then you've got fields of space up at 1048576 and can use tons of that for web stuff.

I am really at a loss for what could be causing this.  Have you gotten any more timeout issues with the netflasher?

**Comment by con-f-use** [comment]
```
confus@confusion:~$ echo -ne "FR\t65536\t1024" | nc 192.168.0.18 7878 -u -w 1 | hexdump -C
00000000  21 46 52 0d 0a                                    |!FR..|
00000005
```

**Comment by cnlohr** [comment]
Wow... I actually never tested this function... It doesn't work.  Will need to fix.  Also, not sure why it crashes sometimes, but... in commonservices.c, under 'F' 'R', modify it so it reads:

```
					buffend += ets_sprintf(buffend, "FR%08d\t%04d\t", nr, datlen ); //Caution: This string must be a multiple of 4 bytes.
					spi_flash_read( nr, (uint32*)buffend, datlen );
					buffend += datlen;
					break;
```

Then issue the following command.  Warning, it may sometimes crash (don't know why);

```
# echo -ne "FR65536\t128" | nc 192.168.4.1 7878 -u -w 1 | hexdump -C
```

**Comment by con-f-use** [comment]
On a working, freshly flashed page (via uart):

```
confus@confusion:dev:~/usr/build/esp82XX-webUI$ echo -ne "FR65536\t128" | nc 192.168.0.18 7878 -u -w 1 | hexdump -C 
00000000  46 52 30 30 30 36 35 35  33 36 09 30 31 32 38 09  |FR00065536.0128.|
00000010  4d 50 46 53 4d 50 46 53  00 00 00 00 00 00 00 00  |MPFSMPFS........|
00000020  00 00 00 00 00 00 00 00  00 01 00 00 00 00 00 00  |................|
00000030  6d 65 6e 75 69 6e 74 65  72 66 61 63 65 2e 6a 73  |menuinterface.js|
00000040  00 00 00 00 00 00 00 00  00 01 00 00 e6 6a 00 00  |.............j..|
00000050  69 6e 64 65 78 2e 68 74  6d 6c 00 00 00 00 00 00  |index.html......|
00000060  00 00 00 00 00 00 00 00  00 6c 00 00 35 06 00 00  |.........l..5...|
00000070  6a 71 75 65 72 79 2d 32  2e 31 2e 34 2e 6d 69 6e  |jquery-2.1.4.min|
00000080  2e 6a 73 2e 67 7a 00 00  00 73 00 00 c3 72 00 00  |.js.gz...s...r..|
00000090
```
And then after I tryed pushing the page through network:
```
./pushtodev 192.168.0.18 65536      page.mpfs
Erase: 1
bufferout: 65536 1024 FW65536	1024	
#[... more of the same ...]
bufferout: 122880 1024 FW122880	1024	
bufferout: 123904 512 FW123904	512	
make[1]: Leaving directory '/home/confus/usr/build/esp82XX-webUI/web'
confus@confusion:dev:~/usr/build/esp82XX-webUI$ echo -ne "FR65536\t128" | nc 192.168.0.18 7878 -u -w 1 | hexdump -C 
00000000  46 52 30 30 30 36 35 35  33 36 09 30 31 32 38 09  |FR00065536.0128.|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000090
```

**Comment by cnlohr** [comment]
The plot thickens! Try using wireshark to look at the FW UDP commands when it's netflashing and see if they look good.

**Comment by con-f-use** [comment]
Here is the [capture log](http://christoph.ist-stylish.de/_data/misc/ele/eps82XX/pushtodev.pcapng). Looks like stuff is getting through.

Note that I removed the ws2812 stuff from page and firmware. But I had the same flashing problems with the unaltered version of your code.

**Comment by con-f-use** [comment]
Btw. the esp8266 seems to do a reset during buring of the fimrware:
```
# uart
ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
```

**Comment by cnlohr** [comment]
Both packet captures do look perfect.  Do either of the attached wireshark dumps come from a failed burn?  Neither of them look like the esp reset.  But, even a device reset shouldn't cause the failures you're seeing.  What confuses me more that I'm thinking about it is that in some of your earlier pictures, it had y's with umlats (which I think is 0xff, but in the FR commands it reads as 0x00.  This makes very little sense.  Perhaps debug by adding printf(...) to the FR command to print out what it's doing and maybe we can get an idea?

As far as cause of crash, I'm not sure. 

Any idea when you get your new ESPs?

**Comment by con-f-use** [comment]
No idea, when the get here. From experience, I'd say next week or so, but sometimes it's 3 days, sometimes its 6 weeks.

In the mean time, I did:
```	case 'w': case 'W':
		if( colon ) {
			colon++;
			const char * colon2 = (const char *) ets_strstr( (char*)colon, "\t" );
			if( colon2 && nr >= 65536) {
				colon2++;
				int datlen = (int)len - (colon2 - pusrdata);
				ets_memmove( buffer, colon2, datlen );

				EnterCritical();
				spi_flash_write( nr, (uint32*)buffer, (datlen/4)*4 );
				ExitCritical();

				ets_memcpy( generic_print_buffer, buffer, 100 );
				generic_print_buffer[100] = '\0';
				uart0_sendStr(generic_print_buffer);

				buffprint( "FW%d\r\n", nr );
				printf( "FW%d\r\n", nr );
				break;
			}
		}
		buffprint( "!FW\r\n" );
	break;
```
To see, if the data gets into the buffer. It does, I see it on the UART. So the only possibility left, I can think of, is that something is wrong with the flash chips on all my modules or with the `spi_write_flash(...)` function of my SDK.

**Comment by cnlohr** [comment]
OH MAN! I just thought of something!  How are you generating the 3.3v for your WI-07/ESP-01?  

I believe all the pins on the ESP-01 are all flash-safe. 

P.S. What's wrong with my libs?

**Comment by con-f-use** [comment]
Either I use my lab power supply or the built-in 3.3V of my USB to Serial Adapter. None of these options seems to have an influence.

I can confirm that the ESP-01 pins are all flash save. I probed around with my multi-meter. No pin is connected to the flash except for VCC and GND.

@libs: see https://github.com/cnlohr/espusb/issues/4#issue-170853483 (you commented on it).

**Comment by cnlohr** [comment]
I used to use built-in 3.3v regulators from my USB to serial adapters and I had issues like what you were describing, except I also got random reboots.  After switching away from that to sold AP1117's or similar chips, a lot of those problems went away.  The NodeMCU uses a legit regulator so I think that's a good candidate if you can get one.

Re: The two single-sided designs I use are now in github, under the "hardware" folder.

**Comment by con-f-use** [comment]
Oh, you're in for a treat. The recent versions are sooo much better. I use the dev repository now:
```
sudo add-apt-repository ppa:js-reynaud/ppa-kicad   # Daily dev-builds
sudo add-apt-repository ppa:js-reynaud/kicad-4       # Stable version
```
Thank you very much for the designs and being and being your charming self!

On the power-hungry little bugger:  Nope, the rail doesn't seem to be the issue here. I hooked it up to my excellent HMP4040 lab power supply. We are talking high cost, quality German engineering. I also gave it a few extra caps and fed it 3.4V just for good measure. Still not working.

**Comment by con-f-use** [comment]
I've added this code in the `FW` branch of `issue_command.c` just after the flash gets written:
```
#ifdef VERIFY_FLASH_WRITE
// uint8_t  __attribute__ ((aligned (32))) buf[1300];
// spi_flash_read( nr, (uint32*)buf, (datlen/4)*4 );
// if( ets_memcmp( buf, buffer, (datlen/4)*4 ) != 0 ) break;
// Rather do it in chunks, to avoid allocationg huge buf
#define VFW_SIZE 128
int jj;
uint8_t  __attribute__ ((aligned (32))) buf[VFW_SIZE];
for(jj=0; jj<datlen; jj+=VFW_SIZE) {
	spi_flash_read( nr+jj, (uint32*)buf, (datlen/4)*4 );
	if( ets_memcmp( buf, buffer+jj, VFW_SIZE ) != 0 ) goto failw;
}
#endif
```
It reads the newly written block of flash in chunks (I wanted to avoid allocation another huge buffer) and verifies it's the same as the data that was passed to `issue_command(....)`. Now the page gets transferred every time, as `pushtodev` retries writing failed blocks. Writing the firmware still gets stuck with retries until timeout, but its a step in the right direction. I made a pull request, that incorporates my changes (as a an option that is per default disabled).

**Comment by cnlohr** [comment]
1) Is it running out of retries on a block erase?
2) When I did espthernet, I cranked the number of retries and speed at which it retried.  Originally with espthernet before it was rock-solid, I had to do this a lot.
3) I have never seen it reset with ColorChord running and netburning.  That's how I did most of my development. Perhaps something has changed in one of the recent stacks?

**Comment by con-f-use** [comment]
1) Yes, always at the[ same point](http://paste.ubuntu.com/23064527/) (address 560128 for my vers. of colorchord)
2) Doesn't help
3) Recent stacks?

**Comment by pelrun** [comment]
What's the flash ID on your modules? Different chips can have different write semantics; the one I tended to hit most was needing to wait a specific amount of time after a write before it was safe to send another command to the chip.

**Comment by con-f-use** [comment]
It reads AH1435 25Q40BI on the chip. I can't read the flash id with esptool.

**Comment by cnlohr** [comment]
OH DUDE.  You can't use a 25Q(0)40 with the net flashing! I mean if you can, it's purely coincidental and you're hitting flash /just right/.  I didn't know that modules with 512kB flash still existed!

So, I /think/ what might be going on is you're trying to write to what it thinks is the scratchpad but it's wrapping back around to address 0, etc.

**Comment by cnlohr** [comment]
Can you post a copy of your .map + .lst file as well as the address it crashes at for a given project?  I am REALLY curious if what's actually going on is if it's crashing when it tries to re-flash the code it's running from.

**Comment by con-f-use** [comment]
> it tries to re-flash the code it's running from
I think that's exactly it. Oh well, at least flashing the page works reliable with my modules and I have others on the way.

For these [files](http://unethische.org/misc/electronics/maplstelfbin.tar.gz), it crashes at  560128.

**Comment by cnlohr** [comment]
I can't believe I hadn't thought of this earlier.  I really can't wait for you to get some NodeMCUs, and some ESP12E/F/S's Also, thanks @pelrun for catching this!!!

**Comment by cnlohr** [comment]
P.S. The crash is in MyRewriteFlash.  Not sure why, though?  I guess what matters is we know what it is.

**Comment by bbkiwi** [comment]
Hi @con-f-use and @cnlohr,  
 I've been testing with the lastest esp82xx/master

The  problem with FR returning !FR mentioned before Charles says " Wow... I actually never tested this function." happen for me also. 

There should not be a \t before the first argument. This works fine: 
   $ echo -ne "FR65536\t1024" | nc 192.168.0.18 7878 -u -w 1 | hexdump -C

**Comment by cnlohr** [comment]
Hmm... wouldn't that only effect reading back from the device?  Also, based on the rest of the commands, I can't tell where it does include the \t.  What file are you referring to?

**Comment by bbkiwi** [comment]
I was only observing that FR returning !FR was caused by a simple mistake, nothing about the rest of the issue. 

The discussion above on 10 Aug 2016 @con-f-use is always putting a tab before the first argument
... you point out he is using nc incorrectly and the 5th comment  on the same date @con-f-use 
After that he is no longer putting the tab first and FR reads the flash ok.

**Comment by con-f-use** [comment]
Thanks for reminding me, I actually wanted to close this a long time ago. As mentioned the issue here was caused by bad (and too small) flash chips on my dirt cheap esp-01 modules.
