### ISSUE TITLE
Questions rather than issues - Embedded 8266

### ISSUE THREAD

**Issue by matjohn2** [cnlohr/colorchord#17]
Hi @cnlohr, AWESOME work! Very impressive!
## Context

Saw this via your IEEE article and wanted to reproduce for my sisters birthday (She's a sax player).
Have the code from the repo compiling and pushed to my device. My build chain is on a mac, so things were a little different; Also, i'd never touched the ESP8266 before, so getting the build environment up and working out howto build/flash was fun in itself. Many thanks to @con-f-use for GIST https://gist.github.com/con-f-use/d086ca941c2c80fbde6d8996b8a50761 and #12 for helping me around the latest SDK build issues.

It's working but I have a couple of questions before i feel confident packaging this up as 'properly working' (Planning to blog this after with build steps for Mac and all the relevant credit 👍 ).
## My question's
1. Mic, Electret mic via a simple pull up resistor and capacitor to input seems to work but requires very loud inputs. pre-amplified to signal-level for things like arduino however seems to overload the input and send the input crazy even in silence. I noticed in bits of your documentation you talk about <1v peak on the mic input, could you give me a little more info on what the chip/code is expecting and your setup for a Mic..
2. Web Interface, all working _apart_ from the 'notes' section. 'notes' just loads the empty div with the 'pause' button in and nothing much else. I'll follow issue #15 where you have uploaded a copy of your web content and will try that, just seems strange that everything else works bar this.
3. General configuration... The docs say I should be tuning things via the pre-processor macros.. yet I seem to be able to change vars in the web interface too. Is this left over from non-embedded colorchord and shouldn't be used? I'm trying to make the LEDs more stable. At the moment i get an occasional lightup when there is no music and I have to be very close to the mic with very loud notes to get a read. I'm hoping this is just due to the first part of my question RE microphone. However I want to know, if I do want to try tweaking FIXBPERO, DFTIIR, Aplitude for notes dissapearing etc... should I only be changing these at compile time, us is the UI safe to use?

I appreciate you probably don't want all these questions; But any help would be greatly received!

Matt

**Comment by con-f-use** [comment]
1. The ADC input on the esp8266 goes into saturation at 1V. Its a hardware constrain and a very unfortunate one. You can of course level shift your signal into the 1V range with a simple op-amp circuit that has enough bandwidth.

**Comment by jalr** [comment]
Hi,
I'm currently working on an assembly kit for the wonderful colorchord based on esp8266.
This is the pre-amp part for the microphone. You can of course omit the 3.5mm jack, R3 and R4 if you don't need a line-in. I use the voltage divider R13,R14 to limit the output voltage to 1V. R9 and R10 should have many kiloohms but both need to have the same value.
If you need the values for the other remaining parts, I can measure them on my prototype board later.
Having an AGC would be nice because correcting the gain manually sucks. Does anybody have a simple circuit for this which is suitable?

![mic_preamp](https://cloud.githubusercontent.com/assets/8084342/17668668/b29e2228-630a-11e6-849f-a108d4a30811.png)

**Comment by cnlohr** [comment]
@matjohn2 : Thank you for your interest I greatly appreciate the community helping with this.  And @con-f-use : Good grief, you're helping out in so many ways I didn't even realize!!! Thank you!

Anyway, to start answering these questions serially...

1) As @con-f-use  says, the ADC reads 1v p-p (0-1v).  This works out for most electret mics, as the volume near where they are read on an instrument like a saxophone is quite loud!  So, just having a resistor, etc. should be enough to drag the signal where it needs to be.  It'll be horribly distorted, but colorchord doesn't care :-p!

2) I agree.  That is strange.  Did you click "restore" on the parameters.  Perhaps something in the parameters got mixed up.

3) Most everything you'll /need/ is in the web gui.  fixbpero, and things like that do have to get changed in compilation step.  Regarding the occasional lightup, try changing 'amp.'  But, you should also watch the oscilloscope to see how much noise is on the line from the power supply.

@jalr I /think/ your design is okay.  Just be careful to watch what drastic changes on the power supply will do.   The ESP is an EMF and electrical disturbance making MACHINE!

**Comment by jalr** [comment]
R13 has 4.3k, R14 has 1.8k
It would be better to use 43k and 18k though but these were the values I had in stock.
The maximum output voltage is then
1800 / (4300+1800) * 3.3 = .974
which is perfectly below the maximum 1V

In the low pass filter I use 1k and 10μ and it sufficiently blocks the EMF from the ESP even though I use a breadboard PCB.
Of course you should pay attention to the ground lines around the opamp so that you don't amplify crap.
For the feedback voltage divider I use a 20k fixed resistor and 2.5k potentiometer which is far away from being perfect. If I use the microphone input the gain is almost maximum and for the line-in it is too high :disappointed:

**Comment by matjohn2** [comment]
Many thanks @cnlohr. The Notes issue seemed to be my browser (all the other bits were working, latest google chrome.) Haven't debugged but it could even be down to plugins/addons adding dynamic code to the page loads. Works fine in Safari 👍 

As for the Mic, Good to know, I've got both a pre-amp providing 1v p2p line output, as well as my homemade resistor+capsule system... I'm not clipping anymore but the noise on the input pin makes the system unusable, @cnlohr How did you get such a beautiful oscilloscope output on your saxophone video? Mine looks like i'm at a rock concert even in silence and is causing me massive issues. (tried batteries vs 5V DC adaptors, and dont think my 5>3.3 Voltage regulator is that bad!).

**Comment by cnlohr** [comment]
Hmm, maybe put the input resistor on an independent regulator to the rest of the system?  Ground loops?  Not sure.  

Btw... clipping is OK! Noise is OK!.  You can turn the amplification down a lot.  Saxophones are LOUD when you put the mic on it.

**Comment by proz0r** [comment]
@jalr, regarding a mic with AGC, I've ordered a MAX9814 module with a mic off eBay - 1V p-p with 1.25V DC bias, with AGC. Putting a 2.5 ratio voltage divider after it should result in a 0.5V-centered waveform that's +/-0.4V (0.8V p-p), I think, which seems perfect.

**Comment by jalr** [comment]
@proz0r Thanks for the hint! I just ordered a module. I think I'm gonna replace my discrete pre-amp in the assembly kit :+1:

**Comment by danover** [comment]
Matjohn2 and jalr, any status updates for the following?
- "Planning to blog this after with build steps for Mac"
- "working on an assembly kit for the wonderful colorchord based on esp8266"
(interested in both)...

**Comment by cnlohr** [comment]
I may be able to do a kit sooner than later.  You should be able to use the OSX build instructions over at esp-open-sdk.

**Comment by Fireflaker** [comment]
It seems like something is wrong with the page.mpfs file I uploaded to 0x10000. The oscilloscope is blank as I connect a signal to pin A0. The parameters are also blank. What may the problem be? Is there a way I can compile the mpfs file on my windows computer?

![img_2712](https://user-images.githubusercontent.com/22672963/30354939-f2c7df0a-97fd-11e7-9cc2-27534c221bfc.PNG)
![img_2713](https://user-images.githubusercontent.com/22672963/30354940-f2dbbf5c-97fd-11e7-8fb8-52e107525e0c.PNG)

**Comment by Fireflaker** [comment]
FIXED. Or bypassed, actually.

It works perfectly fine on the computer browser. However, it does not display properly on the iPad

**Comment by cnlohr** [comment]
That seems very strange.  If you ever figure out why, or what would need to change, let me know with a PR.

**Comment by lightsarefun** [comment]
Considering that this post has been closed for over a year, what is the best solution for the microphone / amplifier?

Has anyone tried the Electret Microphone Amplifier - MAX9814 with a voltage divider?
The auto gain feature will be useful for my application.

**Comment by cnlohr** [comment]
I have not... I recommend prototyping it out and then testing.  It is likely to work fine. 

Right now, though, we do have a *CONFIRMED* absolutely working circuit and it's the Swadge2019 circuit.

https://github.com/cnlohr/swadg2019

**Comment by cnlohr** [comment]
Here you go @lightsarefun  
Audio portion:
![Audio portion of schematic](https://raw.githubusercontent.com/cnlohr/swadge2019/master/hardware/swadge2019_schematic_audio.png)

**Comment by lightsarefun** [comment]
Thanks!
Nice Swadge project. What schematic software are you using?

**Comment by cnlohr** [comment]
Kicad!
