### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by camiloavil** [cnlohr/colorchord#3]
hi

I really like this, after compile it in lubuntu 

I tried to run it but it does not work

into de directory, I type 

./colorchord default.conf

but does not do anything 

in the screen shows "Pulse: from: (null) (PA Test) / 44100x2 (128)"

please help me

Tks

**Comment by cnlohr** [comment]
Hmm... Can you send me the full output?  Also, check the sourcename= line in your default.conf, to see what it reads.  You may have to get pulse to show you all available sound devices.

Also, please post the output of: 
# pactl list | grep Name

**Comment by camiloavil** [comment]
ok I gues the problem is whit that line "sourcename = default" odn default.conf

the next is the full output

Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: sample_channel 1
LF: default.conf
Set: cpu_autolimit 1
Set: title PA Test
Set: set_screenx 720
Set: set_screeny 480
Set: buffer 128
Set: play 0
Set: rec 1
Set: channels 2
Set: samplerate 44100
Set: wininput 0
Set: sample_channel 1
Set: sourcename default
Set: amplify 2.0
Set: base_hz 55.0000
Set: dft_iir 0.6
Set: dft_q 20.0000
Set: dft_speedup 1000.0000
Set: octaves 5
Set: do_progressive_dft 4
Set: filter_iter 2
Set: filter_strength .5
Set: freqbins 24
Set: note_attach_amp_iir 0.2000
Set: note_attach_amp_iir2 0.150
Set: note_attach_freq_iir 0.3000
Set: note_combine_distance 0.5000
Set: note_jumpability 1.8000
Set: note_minimum_new_distribution_value 0.0200
Set: note_out_chop 0.05000
Set: outdrivers OutputVoronoi, DisplayArray
Set: lightx 64
Set: lighty 32
Set: fromsides 1
Set: shape_cutoff 0.03
Set: satamp 5.000
Set: amppow 2.510
Set: distpow 1.500
Loading: OutputVoronoi
Found: OutputVoronoi 0x405e94
Loading: DisplayArray
Found: DisplayArray 0x405edb
Pulse: from: (null) (PA Test) / 44100x2 (128)

Maybe is because I use alsa not pulseaudio?
I dont know 

when I put "pactl list | grep Name" i get
Error en la conexión: Conexión negada
pa_context_connect() falló: Conexión negada

I think is because i dont use pulse

**Comment by camiloavil** [comment]
Wait i just install pulseaudio and it works very well

I see it now. It works with pulseaudio.

Can you tell me if can it work with alsa, or how make it work with the internal sound not with the mic?

thanks a lot

**Comment by cnlohr** [comment]
I know know for your particular setup, but I found that 

    pactl list

will show you a list of available devices.  I use alsa_output.pci-0000_00_1b.0.analog-stereo.monitor on my laptop.

**Comment by camiloavil** [comment]
Perfect thank you very much
it works fine and its awesome

Now i want to do it with the ESP8266

greetings from Colombia

**Comment by cnlohr** [comment]
Splendid :)
