### ISSUE TITLE
Serial Output to Arduino

### ISSUE THREAD

**Issue by xitman327** [cnlohr/colorchord#36]
i dont know much about coding but i am wondering if it can output to a serial so an arduino could receive and change colors to a RGB strip!

**Comment by cnlohr** [comment]
You could probably just hook the RGB strip into the ESP, but... it would not be too hard to add that code-wise.  I don't intend to, myself... So someone else would have to add the feature.

**Comment by xitman327** [comment]
thanks for replying, i will try to learn afew thinks and make it work!! thanks again
