### ISSUE TITLE
.bin for Wemos D1 Mini

### ISSUE THREAD

**Issue by zombodotcom** [cnlohr/colorchord#47]
Could someone post the firmware for colorchord 1 or 2 for the wemos d1 mini? I am having a hard time figuring out how to build this for the nodemcu/ wemos d1 mini

**Comment by cnlohr** [comment]
Is the D1 mini just an ESP12-F? 

My only real concern is that I think we have to know the size of the binary before preparing it for final burning?

**Comment by zombodotcom** [comment]
wemos d1 mini is like a nodemcu 
https://wiki.wemos.cc/products:d1:d1_mini

https://github.com/cnlohr/colorchord/issues/37

[http://imgur.com/a/Pr05O](url)

**Comment by pjmole** [comment]
Here is a binary with esp_iot_sdk_v1.5.2 and ESP_GCC_VERS = 4.8.2 that I am currently using.
[weColor.zip](https://github.com/cnlohr/colorchord/files/1133749/weColor.zip)
I have yet to redo compiler for 4.8.5 use.
