### ISSUE TITLE
Colorchord won't start from commandline, without xserver

### ISSUE THREAD

**Issue by Jobbel** [cnlohr/colorchord#48]
I was trying to run colorchord windowless on a linux system without xserver.
It terminated instantly,
commandline output:

Output Drivers:
OutputCells
DisplayHIDAPI
RecorderPlugin
OutputProminent
DisplayDMX
DisplayUSB2812
DisplayNetwork
DisplayPie
OutputLinear
DisplayArray
OutputVoronoi
null
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: sample_channel -1
LF: fablab.conf
Set: outdrivers OutputLinear, DisplayNetwork
Set: satamp 1.600
Set: sourcename alsa_output.snd-0000_00_1b.0.analog-stereo.monitor
Set: amplify .3
Set: lightx 20
Set: lighty 20

fablab.conf :

#outdrivers = DisplayPie,DisplayNetwork, OutputLinear
outdrivers = OutputLinear, DisplayNetwork
leds = 46
light_siding = 1.0 #Turn this to ~1.9 for more uniformity, ~1.0 for less.
satamp = 1.600
is_loop=0
led_floor = .1 #Turn to .25 for more uniformity, .1 for less.
#note_attach_amp_iir = .3 #.3000
#note_attach_amp_iir2 = .15 #.1500
#note_attach_freq_iir = .3 #0.3000
steady_bright = 0
#dft_iir = 0.0
#dft_q = 20.0000
#dft_speedup = 1000.0000

sourcename = alsa_output.snd-0000_00_1b.0.analog-stereo.monitor
#sourcename = sysdefault

#alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
skipfirst = 1
firstval = 1
port = 7777
address = 192.168.1.185

slope=.10
amplify=.3

lightx = 20
lighty = 20

**Comment by cnlohr** [comment]
set 
```
headless=1
```

**Comment by Jobbel** [comment]
Thank you, this made it work
