### ISSUE TITLE
ESP8266 page abnormal. How to upload?

### ISSUE THREAD

**Issue by Fireflaker** [cnlohr/colorchord#53]
A week ago I made it to work on a NodeMcu board. Later I built a stand alone board for it. I uploaded the two bin files and the page file. But something is wrong. The program seems to not work and the parameters are blank. I tried to upload the page file to 0x10000, 0x100000, and tried the system reflash function on the web page. I also tried using different browsers. None of them works.

![img_2780](https://user-images.githubusercontent.com/22672963/30779320-444b5102-a0bb-11e7-92ec-d95fbd003774.JPG)
![img_2712](https://user-images.githubusercontent.com/22672963/30779321-446617e4-a0bb-11e7-8d78-023107e9165c.PNG)

Are there any suggestions? Thank you.

By the way, thanks for suggesting VB audio virtual cable. Like it.

**Comment by pjmole** [comment]
Hi 
I have found that it is a good idea to "erase_flash" on new/used boards I am unsure of settings.

Then when you have the interface running... you might need to restore parameters to factory settings.

I find it takes a few seconds to get the oscilloscope display running, and the damn browsers often seem to cache too much history so first experimentation needs some reloads...

I am getting nearly 50Hz refresh rates with 320x240 dft with chrome an a Kobo android.

Keep Trying

**Comment by Fireflaker** [comment]
Thank you. I will try write 0 to all 4mb rom

pjmole <notifications@github.com>于2017年9月25日 周一下午8:04写道：

**Comment by cnlohr** [comment]
try

```make initdefault```

**Comment by Fireflaker** [comment]
Right, however, I do not have a Linux system and I am using the "nodemcu firmware programmer" which does has an Initialize function. I tried but it did not work. I will write 0 to all of the 4MB and see if it will work. Thank you for your reply.

**Comment by cnlohr** [comment]
try burning esp82xx/data/esp_init_data_default.bin to 0x3FC000

**Comment by Fireflaker** [comment]
I was flashing it to 0x00000 and that may be the problem. I bought another
esp8266 and it works fine now.
Thank you very much.

CNLohr <notifications@github.com>于2017年10月1日 周日下午12:51写道：

**Comment by Fireflaker** [comment]
I guess it is no longer an issue. I believe the problem will be resolved by doing so. Closing issue. I will update if anything is done. Thank you very much for helping.
