### ISSUE TITLE
Switch digital pinout to TX?

### ISSUE THREAD

**Issue by opus506** [cnlohr/colorchord#55]
Is there a way I can switch the digital pinout to TX?
I received a new type of board that has power drivers already builtin and am unable to change the pins they are connected to.,

**Comment by opus506** [comment]
![esp led baord](https://user-images.githubusercontent.com/15916991/32353805-bbd216de-c005-11e7-90eb-300dad07a1aa.PNG)

**Comment by cnlohr** [comment]
"Digital output pin" what do you mean?

**Comment by opus506** [comment]
Currently the RX pin that is used to output the digital data to the LEDs.

**Comment by cnlohr** [comment]
Ah, that's because that's the only pin that the I2S engine is connected to.  No other pins can be used for mid- or high- performance WS2812B output, that I'm aware of.  Is there a project that says otherwise?

**Comment by opus506** [comment]
the ws2812fx project gives the option to use gpio 0 or 2. I'm not not sure if it's a different circumstance or not.

**Comment by cnlohr** [comment]
It says free of delays but then relies on the NeoPixel library, which does effectively delay by spinning.   There's not really time to spin and do LED work when you're doing all the crazy audio processing :-/.  It could be ported and could probably support 20 pixels or so but I don't have code ready to do it.  All you would have to do is swap out the functions in the  ws2812_i2s.c file.

**Comment by opus506** [comment]
ok wow. I understand now.
I'll just modify the hardware ever so slightly.

Thanks


On Nov 6, 2017 16:10, "CNLohr" <notifications@github.com> wrote:

It says free of delays but then relies on the NeoPixel library, which does
effectively delay by spinning. There's not really time to spin and do LED
work when you're doing all the crazy audio processing :-/. It could be
ported and could probably support 20 pixels or so but I don't have code
ready to do it. All you would have to do is swap out the functions in the
ws2812_i2s.c file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cnlohr/colorchord/issues/55#issuecomment-342271198>,
or mute
the thread

**Comment by cnlohr** [comment]
I would also point out to the manufacturer that it would be good if it could be configured.

Another option is SPI output, though I haven't messed with it.

**Comment by cnlohr** [comment]
Maybe GPIO13.  But TX(GPIO3) code's already done.
