### ISSUE TITLE
USB Audio Input on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by mbc1855** [cnlohr/colorchord#56]
Hi,
I'm attempting to run Colorchord2 on a headless Raspberry Pi Zero Wireless.  I'm using a USB PnP Mic and no audio output; my goal is to use the audio input from the mic to control a short string of NeoPixels.  The goal is that the Pi will boot with a read-only disk and begin controlling the NeoPixels until someone unplugs the power.  The mic is the only input device, the NeoPixels the only output device.  

Unfortunately I seem to be getting an error related to the audio input as shown below.

Output is as follows:
```
pi@MIC-4FQ4:~ $ sudo colorchord /home/pi/colorchord-master/colorchord2/default.conf
Output Drivers:
	OutputCells
	DisplayHIDAPI
	RecorderPlugin
	OutputProminent
	DisplayDMX
	DisplayUSB2812
	DisplayNetwork
	DisplayPie
	OutputLinear
	DisplayArray
	OutputVoronoi
	null
   Warning: cannot open default.conf.
   LF: /home/pi/colorchord-master/colorchord2/default.conf
   Set: headless 1
   Set: cpu_autolimit 1
   Set: set_screenx 720
   Set: set_screeny 480
   Set: sound_source ALSA
   Set: sample_channel -1
   Loading: OutputVoronoi
   Found: OutputVoronoi 0x1739c
   Loading: DisplayArray
   Found: DisplayArray 0x17248
   Initializing sound.  Recommended driver: ALSA
   U: record = 1
   U: devrecord = default
   cannot open input audio device (No such file or directory)
   ERROR: Failed to initialize sound output device
```

lsusb gives me the following:
```
pi@MIC-4FQ4:~ $ lsusb
Bus 001 Device 003: ID 08bb:2902 Texas Instruments PCM2902 Audio Codec
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Alsamixer sees the USB mic as a " USB PnP Sound Device" and an id of hd:1.

What am I doing wrong?

Thanks,
Ian

**Comment by mbc1855** [comment]
I added the following to default.conf and got further along, but I'm not sure that the source is properly setup, and I still end up with colorchord exiting prematurely.
```
record = 0
devrecord = null
sourcename = alsa_input.usb-20980000.usb-1
```

```
pi@MIC-4FQ4:~/colorchord-master/colorchord2 $ ./colorchord 
Output Drivers:
	OutputCells
	DisplayHIDAPI
	RecorderPlugin
	OutputProminent
	DisplayDMX
	DisplayUSB2812
	DisplayNetwork
	DisplayPie
	OutputLinear
	DisplayArray
	OutputVoronoi
	null
Set: headless 1
Set: cpu_autolimit 1
Set: set_screenx 0
Set: set_screeny 0
Set: sound_source ALSA
Set: sample_channel -1
Loading: OutputVoronoi
Found: OutputVoronoi 0x1739c
Loading: DisplayArray
Found: DisplayArray 0x17248
Initializing sound.  Recommended driver: ALSA
24 5 55.000000 20.000000 2.000000
Set: headless 1
Set: cpu_autolimit 1
Set: title PA Test
Set: set_screenx 0
Set: set_screeny 0
Set: buffer 384
Set: play 0
Set: rec 0
Set: channels 1
Set: samplerate 44100
Set: wininput 1
Set: sound_source ALSA
Set: sample_channel -1
Set: record 0
Set: devrecord null
Set: sourcename alsa_input.usb-20980000.usb-1
Set: amplify 2.0
Set: base_hz 55
24 5 55.000000 20.000000 2.000000
Set: dft_iir 0.6
Set: dft_q 20.0000
Set: dft_speedup 1000.0000
Set: octaves 5
24 5 55.000000 20.000000 2.000000
Set: do_progressive_dft 4fa
Set: filter_iter 2
Set: filter_strength .5
Set: freqbins 24
24 5 55.000000 20.000000 2.000000
Set: note_attach_amp_iir 0.3500
Set: note_attach_amp_iir2 0.250
Set: note_attach_freq_iir 0.3000
Set: note_combine_distance 0.5000
Set: note_jumpability 1.8000
Set: note_minimum_new_distribution_value 0.0200
Set: note_out_chop 0.05000
Set: outdrivers OutputVoronoi, DisplayArray
Set: lightx 7
Set: lighty 1
Set: fromsides 1
Set: shape_cutoff 0.03
Set: satamp 5.000
Set: amppow 2.510
Set: distpow 1.500
Segmentation fault
```

If I run it as root then it doesn't throw the segmentation fault at the end, but it still exits.

**Comment by cnlohr** [comment]
hmm... what happens if you set it to default

Also, please execute the following:

```
pactl list
```

**Comment by mbc1855** [comment]
Sorry, got away from this for a bit.

When I set it to default I had the same result.  No change at all.

I didn't have Pulse Audio installed so I remedied that, but now have this when I run "pactl list"
`
pi@MIC-4FQ4:~/colorchord-master/colorchord2 $ pactl list
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
`

**Comment by cnlohr** [comment]
How did you install it?  

```
 sudo apt-get install pulseaudio 
```
?
You may also need to reboot.

**Comment by kevinpanaro** [comment]
I'm doing something similar with a raspberry pi zero W, except using shairport-sync and attempting to pipe that through to colorchord, with little success. I'm getting the same error as you are though, and it mostly always fails with Segmentation fault.

**Comment by cnlohr** [comment]
What does ```pactl list``` show?

**Comment by kevinpanaro** [comment]
A lot. 

Source shows this

Source #0
	State: IDLE
	Name: alsa_output.platform-soc_sound.analog-stereo.monitor
	Description: Monitor of snd_rpi_hifiberry_dac Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 6
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor of Sink: alsa_output.platform-soc_sound.analog-stereo
	Latency: 0 usec, configured 2000000 usec
	Flags: DECIBEL_VOLUME LATENCY
	Properties:
		device.description = "Monitor of snd_rpi_hifiberry_dac Analog Stereo"
		device.class = "monitor"
		alsa.card = "0"
		alsa.card_name = "snd_rpi_hifiberry_dac"
		alsa.long_card_name = "snd_rpi_hifiberry_dac"
		alsa.driver_name = "snd_soc_hifiberry_dac"
		device.bus_path = "platform-soc:sound"
		sysfs.path = "/devices/platform/soc/soc:sound/sound/card0"
		device.string = "0"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card"
	Formats:
		pcm

**Comment by cnlohr** [comment]
Try editing default.conf and change the sourcename line in default.conf as follows.

```sourcename = default```

to

```sourcename = alsa_output.platform-soc_sound.analog-stereo.monitor```

**Comment by kevinpanaro** [comment]
I tried that and received this output.

Output Drivers:
	OutputCells
	DisplayHIDAPI
	RecorderPlugin
	OutputProminent
	DisplayDMX
	DisplayUSB2812
	DisplayNetwork
	DisplayPie
	OutputLinear
	DisplayArray
	OutputVoronoi
	null
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: sound_source ALSA
Set: sample_channel -1
Segmentation fault

I'm also using a phat dac, but i'm not sure how that might have an effect.

**Comment by cnlohr** [comment]
Are you running on a GUI or not?  If no gui, you will need to set ```headless = 1```

**Comment by kevinpanaro** [comment]
That helped a little bit.

Output Drivers:
	OutputCells
	DisplayHIDAPI
	RecorderPlugin
	OutputProminent
	DisplayDMX
	DisplayUSB2812
	DisplayNetwork
	DisplayPie
	OutputLinear
	DisplayArray
	OutputVoronoi
	null
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: headless 1
Set: sound_source ALSA
Set: sample_channel -1
Loading: OutputVoronoi
Found: OutputVoronoi 0x172e8
Loading: DisplayArray
Found: DisplayArray 0x17194
Initializing sound.  Recommended driver: ALSA
U: record = 1
U: devrecord = default
24 5 55.000000 20.000000 2.000000
Set: cpu_autolimit 1
Set: title PA Test
Set: set_screenx 720
Set: set_screeny 480
Set: headless 1
Set: buffer 384
Set: play 0
Set: rec 1
Set: channels 2
Set: samplerate 44100
Set: wininput 1
Set: sound_source ALSA
Set: sample_channel -1
Set: sourcename alsa_output.platform-soc_sound.analog-stereo.monitor
Set: amplify 2.0
Set: base_hz 55
24 5 55.000000 20.000000 2.000000
Set: dft_iir 0.6
Set: dft_q 20.0000
Set: dft_speedup 1000.0000
Set: octaves 5
24 5 55.000000 20.000000 2.000000
Set: do_progressive_dft 4fa
Set: filter_iter 2
Set: filter_strength .5
Set: freqbins 24
24 5 55.000000 20.000000 2.000000
Set: note_attach_amp_iir 0.3500
Set: note_attach_amp_iir2 0.250
Set: note_attach_freq_iir 0.3000
Set: note_combine_distance 0.5000
Set: note_jumpability 1.8000
Set: note_minimum_new_distribution_value 0.0200
Set: note_out_chop 0.05000
Set: outdrivers OutputVoronoi, DisplayArray
Set: lightx 64
Set: lighty 32
Set: fromsides 1
Set: shape_cutoff 0.03
Set: satamp 5.000
Set: amppow 2.510
Set: distpow 1.500
Segmentation fault

still result in Segmentation fault.

**Comment by cnlohr** [comment]
Any way you can run this against gdb to try to get a log.

You may need to modify the Makefile to enable debugging ```-O0 -g``` instead of ```-Os -s```

Charles

**Comment by kevinpanaro** [comment]
I'm not familiar with gdb but can check it out.

I noticed the flags were set to -0s -g, so i tried changing it to -0s -s, and got here.

Output Drivers:
	OutputCells
	DisplayHIDAPI
	RecorderPlugin
	OutputProminent
	DisplayDMX
	DisplayUSB2812
	DisplayNetwork
	DisplayPie
	OutputLinear
	DisplayArray
	OutputVoronoi
	null
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: headless 1
Set: sample_channel -1
Loading: OutputVoronoi
Found: OutputVoronoi 0x17328
Loading: DisplayArray
Found: DisplayArray 0x171d4
Initializing sound.  Recommended driver: PULSE
Pulse: from: alsa_output.platform-soc_sound.analog-stereo.monitor (PA Test) / 44100x2 (384)

**Comment by kevinpanaro** [comment]
I'm not sure if this is helpful, but when running gdb, I find this:

Thread 1 "colorchord" received signal SIGSEGV, Segmentation fault.
0xb6c8537c in XSetForeground () from /usr/lib/arm-linux-gnueabihf/libX11.so.6

There's more I can get from gdb, I presume.

**Comment by cnlohr** [comment]
Ah, yes! 

You will need to set headless to 1 in default.conf, otherwise it will attempt to open a display. 

Alternatively, you can run it from the GUI.

Charles

**Comment by kevinpanaro** [comment]
makes sense, will do. running the pi headless, so running colorchord headless would makes sense. I'll update if it works.

**Comment by kevinpanaro** [comment]
Is the output for the LEDs the TX pin (physical pin 8) on the raspberry pi zero? I'm not getting any action.

**Comment by kevinpanaro** [comment]
Alright last update. It works. The problem is the phat dac (a raspberry pi zero dac hat) doesn't output through pulse audio, so in alsamixer, if I mute pulse audio, it won't mute the sound thats coming out of the speakers, and that's apparently where colorchord is looking. I tested it with a gui with a speaker test, that does use pulse audio in alsamixer and colorchord responds.

**Comment by cnlohr** [comment]
wat? I don't remember anyone ever writing anything to output on the rpi's GPIOs!

Most of the physical output mechanisms are over Ethernet or USB.

**Comment by kevinpanaro** [comment]
Yeah my bad, i'm dense.

**Comment by cnlohr** [comment]
Nah, all is good.  You know... you could probably drop in some ws2812b output library for the pi and give it a whirl by adding an output driver to colorchord.
