### ISSUE TITLE
Question about unable to connect to the esp8266

### ISSUE THREAD

**Issue by Fireflaker** [cnlohr/colorchord#57]
Hi,
I am uploading these files to an ESP8266. After finished, I got the boot mood printed on the serial monitor and am not able to connect to "ESP_xxxxx". Any suggestions, please?

![image](https://user-images.githubusercontent.com/22672963/35477127-b632ed5c-038a-11e8-893a-342016cd10c0.png)

**Comment by cnlohr** [comment]
(1) I don't know if that's the right address for the init data, maybe?
(2) You can try to press-and-hold the PGM button (not reset) for 10 seconds, it should reset it to factory settings

**Comment by Fireflaker** [comment]
Thanks. I figured it out. 
![image](https://user-images.githubusercontent.com/22672963/35478878-fa54a102-03b6-11e8-90cc-ab8d755bcb68.png)

I will try to make one for ESP32 and hopefully, it won't be too hard. (It probably will)

**Comment by Fireflaker** [comment]
Just found a library for ESP32 ADC
https://github.com/G6EJD/ESP32-ADC-Accuracy-Improvement-function
