### ISSUE TITLE
Question about embeding in Respberry Pi zero

### ISSUE THREAD

**Issue by Fireflaker** [cnlohr/colorchord#58]
Hi
How should I embed the color chord onto a raspberry pi zero, please? I want to control a 300LED strip and due to the limitation in RAM space of the ESP8266, it can only do  255 LEDs. Should I first install ubuntu? Also, which ADC should I use?
Thanks...

**Comment by cnlohr** [comment]
You can just use ColorChord2.  It will work just fine on the rpi, and it's a regular Linux app.  The only issue is driving the LEDs.  I don't know of any libraries you can use for that.

**Comment by Fireflaker** [comment]
Thanks a lot

**Comment by tjd195** [comment]
@Fireflaker were you able to find libraries to drive the LEDs? I am currently working on using colorchord2 on a pi and I am currently not even getting a display window after correctly installing everything.

**Comment by CaiB** [comment]
What type of LEDs? If you want to use something like the WS2812, they have reasonably strict timing requirements that you're not going to be able to adhere to with a software-based solution. Not sure if the Pi has any DMA that would be useful here.

**Comment by tjd195** [comment]
@CaiB I have this LED: https://www.adafruit.com/product/1461?length=3

**Comment by CaiB** [comment]
> The protocol used is very very timing-specific and can only be controlled by microcontrollers with highly repeatable 100ns timing precision.

That's not happening from software, where the OS will just randomly pause your program for thousands of ns. You'll have to either figure out how to use DMA on the Pi (I'm not sure it even has any), or use another device like a microcontroller.

**Comment by tjd195** [comment]
@CaiB so this would work?
https://www.adafruit.com/product/2821

**Comment by CaiB** [comment]
Yeah, that's just an ESP8266 dev board. There is a version of colorchord that can run directly on there, removing the need for a Pi or computer entirely. Alternatively, you can run colorchord on another device, send the data to the ESP, and have it just translate the data to LED commands.
