### ISSUE TITLE
Yellow is not quite yellow

### ISSUE THREAD

**Issue by jasonspriggs** [cnlohr/colorchord#59]
I was playing Yellow Submarine on my colorchord and was SORELY disappointed when the yellow was more... green/blue than yellow when they said yellow. I will say though, I was glad that "Sky of blue" was indeed blue, but "sea of green" was quite light blue for a green.

2/5 might chord again

https://youtu.be/gr1Bc0g0jQ0

**Comment by cnlohr** [comment]
You have to turn on submarine mode in F.  Edit default.conf and set base_hz to 43.65.

```base_hz = 43.65```

You will no longer suffer from sad submarine blues.
