### ISSUE TITLE
Question building for Windows.

### ISSUE THREAD

**Issue by Fireflaker** [cnlohr/colorchord#64]
Hello,
I tried building colorchord for Windows 10 and it looks like this
![image](https://user-images.githubusercontent.com/22672963/40493534-ef2aad0e-5f40-11e8-8d3e-f30559b6043e.png)

The audio works fine but there is no visual output. Is there something I need to configure? Thank you.

**Comment by cnlohr** [comment]
Can you paste the entire output, earlier on of the application?  It may be unable to find the other tools.

What is your build environment TCC or GCC (mingw)?  Note that visual studio is not supported :-/.

**Comment by xiongyihui** [comment]
I also don't get it work on windows.

Built with TCC (compile.bat) on Windows 10 64bit surfacebook

The log is:

```
Output Drivers:
        DisplayNetwork
        DisplayArray
        DisplayHIDAPI
        DisplayOutDriver
        DisplayPie
        null
        OutputCells
        OutputLinear
        OutputProminent
        OutputVoronoi
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: sample_channel -1
Loading: OutputVoronoi
Found: OutputVoronoi 000000000041002C
Loading: DisplayArray
Found: DisplayArray 0000000000405FD0
Initializing sound.  Recommended driver: WIN
Buffer: 384
WFMT Size (debugging temp for TCC): 18
WFMT: 2 44100 88200
Wave Devs: 1; WAVE_MAPPER: -1; Selected Input: 1
waveInOpen: 0000000002873E18, 000000000014ED1A
WIO: 2
WIS: 5
24 5 55.000000 20.000000 2.000000
Set: cpu_autolimit 1
Set: title PA Test
Set: set_screenx 720
Set: set_screeny 480
Set: buffer 384
Set: play 0
Set: rec 1
Set: channels 2
Set: samplerate 44100
Set: wininput 1
Set: sample_channel -1
Set: sourcename default
Set: amplify 2.0
Set: base_hz 55
24 5 55.000000 20.000000 2.000000
Set: dft_iir 0.6
Set: dft_q 20.0000
Set: dft_speedup 1000.0000
Set: octaves 5
24 5 55.000000 20.000000 2.000000
Set: do_progressive_dft 4fa
Set: filter_iter 2
Set: filter_strength .5
Set: freqbins 24
24 5 55.000000 20.000000 2.000000
Set: note_attach_amp_iir 0.3500
Set: note_attach_amp_iir2 0.250
Set: note_attach_freq_iir 0.3000
Set: note_combine_distance 0.5000
Set: note_jumpability 1.8000
Set: note_minimum_new_distribution_value 0.0200
Set: note_out_chop 0.05000
Set: outdrivers OutputVoronoi, DisplayArray
Set: lightx 64
Set: lighty 32
Set: fromsides 1
Set: shape_cutoff 0.03
Set: satamp 5.000
Set: amppow 2.510
Set: distpow 1.500
Button: 691,95 (1) -> 1
Button: 691,95 (1) -> 0
```

![image](https://user-images.githubusercontent.com/948283/40885594-d96b79e4-675b-11e8-8bd9-1d62fd2e4e01.png)

**Comment by cnlohr** [comment]
You likely need to change the ```wininput```.  Try setting it to different values in default.conf.  Try values from -1 to about 8.

**Comment by Fireflaker** [comment]
Thanks!

**Comment by Fireflaker** [comment]
Tried wininput=8 and wininput=1, both do not work.
Tried wininput=-1, works.
The default is wininput=1, does not work, recommend to update the default.conf.

To minimize the suffering of newbies trying to build the exe for windows, may I upload some generated ColorChord exe files?

**Comment by cnlohr** [comment]
I'll make that change, and yes, you may.  Please only upload one.

**Comment by JINODK** [comment]
Me too, changed the wininput value but still no luck, no mic detected
Log:
```
Output Drivers:
        DisplayNetwork
        DisplayArray
        DisplayHIDAPI
        DisplayOutDriver
        DisplayPie
        null
        OutputCells
        OutputLinear
        OutputProminent
        OutputVoronoi
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: sample_channel -1
Loading: OutputVoronoi
Found: OutputVoronoi 0000000000410240
Loading: DisplayArray
Found: DisplayArray 0000000000405FD0
Initializing sound.  Recommended driver: WIN
Buffer: 384
WFMT Size (debugging temp for TCC): 18
WFMT: 2 44100 88200
Wave Devs: 1; WAVE_MAPPER: -1; Selected Input: -1
waveInOpen: 0000000000A2EED8, 000000000014ED1A
Mic Open.
WIO: 0
WIS: 0
24 5 55.000000 20.000000 2.000000
Set: cpu_autolimit 1
Set: title PA Test
Set: set_screenx 720
Set: set_screeny 480
Set: buffer 384
Set: play 0
Set: rec 1
Set: channels 2
Set: samplerate 44100
Set: wininput -1
Set: sample_channel -1
Set: sourcename default
Set: amplify 2.0
Set: base_hz 55
24 5 55.000000 20.000000 2.000000
Set: dft_iir 0.6
Set: dft_q 20.0000
Set: dft_speedup 1000.0000
Set: octaves 5
24 5 55.000000 20.000000 2.000000
Set: do_progressive_dft 4
Set: filter_iter 2
Set: filter_strength .5
Set: freqbins 24
24 5 55.000000 20.000000 2.000000
Set: note_attach_amp_iir 0.3500
Set: note_attach_amp_iir2 0.250
Set: note_attach_freq_iir 0.3000
Set: note_combine_distance 0.5000
Set: note_jumpability 1.8000
Set: note_minimum_new_distribution_value 0.0200
Set: note_out_chop 0.05000
Set: outdrivers OutputVoronoi, DisplayArray
Set: lightx 64
Set: lighty 32
Set: fromsides 1
Set: shape_cutoff 0.03
Set: satamp 5.000
Set: amppow 2.510
Set: distpow 1.500
```

Maybe there any setting to make it work? Also the compile.bat don't work anymore.
![untitled](https://user-images.githubusercontent.com/36285359/50044884-c0341080-00bc-11e9-8769-e699439e3116.png)

**Comment by cnlohr** [comment]
@JINODK I am able to reproduce the issue.  Looking into it now.

**Comment by cnlohr** [comment]
@JINODK I am able to reproduce the issue.  Looking into it now. On initial investigation it looks like some sort of weird 64-bit 32-bit problem.

**Comment by JINODK** [comment]
The windows is just normal for me, until windows 10. When i use ubuntu, it just work fine.
Also i only use one microphone input, others are disabled.
![image](https://user-images.githubusercontent.com/36285359/50049125-76284a80-010f-11e9-9987-f233f7da9d67.png)
![image](https://user-images.githubusercontent.com/36285359/50049130-83ddd000-010f-11e9-9a9d-327fdace77a6.png)

**Comment by cnlohr** [comment]
@JINODK  Do you know which compiler exactly you are using?  I can't seem to get this to work with the 64-bit compiler at all.

**Comment by JINODK** [comment]
I use tiny C compiler, that's the only thing i can see on your compile.bat

**Comment by JINODK** [comment]
Also i don't know why i'm not able to use the makefile with the mingw32-make command to create the program too, it seems like missing something
```
$ mingw32-make colorchord.exe
i686-w64-mingw32-gcc -g -DICACHE_FLASH_ATTR= -I../embeddedcommon -I. -O1    -o colorchord.exe os_generic.c main.c dft.c decompose.c filter.c color.c notefinder.c util.c outdrivers.c DrawFunctions.c parameters.c chash.c WinDriver.c sound.c sound_null.c sound_win.c OutputVoronoi.c OutputProminent.c DisplayArray.c OutputLinear.c DisplayPie.c DisplayNetwork.c hook.c RecorderPlugin.c ../embeddedcommon/DFT32.c OutputCells.c configs.c hidapi.c DisplayHIDAPI.c -lwinmm -lgdi32 -lws2_32  -lsetupapi
process_begin: CreateProcess(NULL, i686-w64-mingw32-gcc -g -DICACHE_FLASH_ATTR= -I../embeddedcommon -I. -O1 -o colorchord.exe os_generic.c main.c dft.c decompose.c filter.c color.c notefinder.c util.c outdrivers.c DrawFunctions.c parameters.c chash.c WinDriver.c sound.c sound_null.c sound_win.c OutputVoronoi.c OutputProminent.c DisplayArray.c OutputLinear.c DisplayPie.c DisplayNetwork.c hook.c RecorderPlugin.c ../embeddedcommon/DFT32.c OutputCells.c configs.c hidapi.c DisplayHIDAPI.c -lwinmm -lgdi32 -lws2_32 -lsetupapi, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:25: recipe for target 'colorchord.exe' failed
mingw32-make: *** [colorchord.exe] Error 2
```

**Comment by JINODK** [comment]
It wokred! Thanks

**Comment by JINODK** [comment]
ok, mine is 64 bit, may i leave the exe in your colorchord 2 so other people can do it easily ?

**Comment by JINODK** [comment]
Bad new: the compile.bat don't want to work anymore

**Comment by cnlohr** [comment]
Yes.

Can you please give your exact compilation lines here?

**Comment by cnlohr** [comment]
(as I was unable to get 64-bit working at all)

**Comment by JINODK** [comment]
Ok i can run it now
i think maybe add the "pause" in the compile.bat so it make people who haven't install tcc yet can read the cmd properly, because it just like a cmd window just flash through when it can't find the tcc.

**Comment by cnlohr** [comment]
So you are compiling with 64-bit TCC?!?

**Comment by JINODK** [comment]
Yeah

**Comment by cnlohr** [comment]
@JINODK  Can you give me your exact compilation lines? 

Are you on the current master branch?? 

My 64-bit has this mystery failure where the MMSystem callback is never being called.

**Comment by JINODK** [comment]
This is all file i have downloaded to make colorchord
https://drive.google.com/open?id=1xvSa6NEZ8QXzNIkcMzAy6tBf62wQVKBw
