### ISSUE TITLE
No Audio on Windows

### ISSUE THREAD

**Issue by CaiB** [cnlohr/colorchord#68]
Hey Charles,

I'm trying to get this working on Windows, and am having a really hard time. This is on my laptop, which as a microphone, and I also tried installing Virtual Audio Cable to capture output as another input device. I can see in the settings that both devices are receiving sound, but ColorChord seems to be getting no signal.

I tried `wininput` values of -1 through 8. Here is the output when I try -1:
```
Output Drivers:
        DisplayNetwork
        DisplayArray
        DisplayHIDAPI
        DisplayOutDriver
        DisplayPie
        null
        OutputCells
        OutputLinear
        OutputProminent
        OutputVoronoi
Set: cpu_autolimit 1
Set: set_screenx 720
Set: set_screeny 480
Set: sample_channel -1
Loading: OutputVoronoi
Found: OutputVoronoi 0000000000410022
Loading: DisplayArray
Found: DisplayArray 0000000000405FD0
Initializing sound.  Recommended driver: WIN
Buffer: 384
WFMT Size (debugging temp for TCC): 18
WFMT: 2 44100 88200
Wave Devs: 2; WAVE_MAPPER: -1; Selected Input: -1
waveInOpen: 0000000002753BF8, 000000000014ED1A
Mic Open.
WIO: 0
WIS: 0
24 5 55.000000 20.000000 2.000000
```

Devices -1, 0, and 1 cause WIO and WIS to output 0. Other devices cause an output of 2, 5 respectively (I assume this means it couldn't open that device, since those don't exist).

ColorChord sadly just sits there, with a black screen, and all 0s.

I was able to get it working on Ubuntu fine, but would rather avoid using that as it doesn't fit into my intended application.

Do you have any suggestions as to what I could try in order to get it working?

Thanks!

**Comment by cnlohr** [comment]
Have you tried using a tool like audacity to record data from the sound card to verify that at least one or two of your inputs are working as expected?

**Comment by CaiB** [comment]
I just tried it, Audacity is able to record both inputs, and produces exactly the audio I expect. (Mic audio on the Mic, what is playing from other programs on the Virtual Audio Cable interface).

**Comment by CaiB** [comment]
Interesting... It appears that it doesn't get called.

I added a `printf` in the main area (to make sure my compilation setup worked, which did get output, so it definitely did compile a new version). I then added this on line 105 (right before `int i;`: `printf( "Sound %d %d\n", in[0], samplesr );` None of these lines ever showed up on the console.

**Comment by CaiB** [comment]
I also just tried it on my other computer, with different virtual audio interface software (also tested with Audacity), and got exactly the same result.

If it's relevant, I'm on Windows 10.0.17134.112 (1803 branch) Professional 64b.

**Comment by cnlohr** [comment]
O.O;; hmm... that means that the sound callback is never called back. I don't actually know how to begin to debug that.

**Comment by CaiB** [comment]
I've been doing a bit of digging, trying to understand your code. If I'm not mistaken, you're using the older Wave audio APIs, which I think are mostly superseded now. I'm attempting an [implementation of ColorChord in C#](https://github.com/CaiB/ColorChord.NET) using the new (as in since Vista) Core Audio APIs, which sounds like the more up-to-date way of accessing audio on Windows.  
In particular, I'll be referencing [this](https://docs.microsoft.com/en-us/windows/desktop/CoreAudio/loopback-recording).  
I'm quite the opposite of an expert on this though, I'll let you know if I get anywhere.

**Comment by CaiB** [comment]
Quick question: In [default.conf:62](https://github.com/cnlohr/colorchord/blob/master/colorchord2/default.conf#L62), `do_progressive_dft` is set to `4fa`, but in the code it's switching on a number, and resulting in 4. What does the "fa" do here, and where does it go?

**Comment by cnlohr** [comment]
Whoops.  That's a type-o.  It should just be '4'

**Comment by cnlohr** [comment]
Good catch.  Committed.

**Comment by CaiB** [comment]
Alright, I figured that was the case.

One more thing I noticed, when compiling on Windows, I get the following warning:
`../sound_win.c:138: warning: assignment makes pointer from integer without a cast`
Is it possible that this might be related to the original issue?

**Comment by cnlohr** [comment]
Wait a minute --- are you compiling for Win64?  If so I never tested that.  Try targeting Win32.

Also, there is a build-in-windows thing for TinyCC you can test. https://github.com/cnlohr/colorchord/blob/master/colorchord2/windows/compile.bat

**Comment by CaiB** [comment]
That is what I'm running, I couldn't get the `mingw32-make` method to work.

Is there something special I need to do on the TCC one in order to target x86?

**Comment by CaiB** [comment]
Update on my project: I actually have basic functionality working now (somehow). My version now listens to system audio (what is playing through the speakers, not mic), does the calculations for a linear 50 LED string, then shoots that out over the network to my receiver.

It doesn't have the awesome extensibility of your system and is still pretty rough, so I'll work on making it a bit nicer.

The output colours on my implementation don't fully match with what your system outputs either. I'm sure there was some original guiding idea behind how the music scale maps to colours, would you mind sharing that? (e.g. C should map to yellow, etc).

**Comment by cnlohr** [comment]
I guess I'm surprised it's worth that instead of writing the 50-60 lines for making a Windows Core Audio driver for colorchord... BUT... You are probably looking for the `CCtoHEX` function.

**Comment by CaiB** [comment]
Heh, I figured you would say that. My justifications are that I wanted to integrate this with another C#-based project of mine, and my unfamiliarity with raw C would probably have made me trying to write the Core Audio stuff in C a more time consuming and less fun process.

Also, I've been surprised at just how performant my implementation still is. Without a GUI, outputting 50 LEDs via UDP at about 90Hz uses <0.3% CPU and <8MB RAM.

I have seen the CCtoHEX function (had to modify it in my implementation). I was wondering more what your numbers were based off. I assume you had at least one note -> colour mapping that you based the spectrum location off of, right? (for example, you may have had C being Yellow in mind).

**Comment by cnlohr** [comment]
Well, yellow is just the "root" note in the tests I ran with a bunch of people.  It seems to perform marginally better if the root note matches the root note of the song, but it's still cool either way.

**Comment by CaiB** [comment]
Ah, I see. One more question about your colours, sorry. Am I correct in understanding that your version has a pretty non-linear note-to-hue mapping?  
I'm understanding your code doing this:  
- lower 1/3 of the music scale goes to yellow-red (1/6 of the colour spectrum)
- middle 1/3 of the music scale goes to red-blue (2/6 of the colour spectrum)
- higher 1/3 of the music scale goes to blue-yellow (3/6 of the colour spectrum)

Is this accurate?

**Comment by cnlohr** [comment]
There is a colorwheel on this page: http://cnlohr.blogspot.com/2010/11/colorchord-sound-lighting.html

**Comment by CaiB** [comment]
Ah, this is perfect. Thanks!

Do you want to close this issue now? I'm not sure if anyone else is experiencing the original issue, and I don't really need it resolved anymore myself. That said, if you do want to work on it at all, I'd be happy to try and help (since it does seem like it might be specific to something I'm doing).

I'm continuing to work on my C#.NET re-implementation, and am currently working on making it as/more extensible and easily configurable as your current one. I'll let you know when I get to a state where I'm happy with it if you're at all interested.

**Comment by cnlohr** [comment]
All I ask is you give me credit somewhere :-p ... But yeah, let's close this.
