### ISSUE TITLE
Not compiling for windows

### ISSUE THREAD

**Issue by RoanBrand** [cnlohr/colorchord#7]
After a long struggle with MinGW and Cygwin I have finally given up after having partial success with Cygwin.

The only dependency not available for windows is the alsa sound lib - specifically alsa/asoundlib.h

Please post if I am missing something or if this will never work on windows.

Roan

**Comment by cnlohr** [comment]
It should be able to work on Windows, however, not with Alsa.  I just updated the Makefile for use with mingw.   I can't run it on Linux, but it built just fine.  Try dropping this in the 'colorchord2' folder and running it.



[colorchord.exe.zip](https://github.com/cnlohr/colorchord/files/179110/colorchord.exe.zip)
