### ISSUE TITLE
WS_RETKEY_SIZEM1 and WS_RETKEY_SIZE - which is right?

### ISSUE THREAD

**Issue by king2** [cnlohr/colorchord#71]
in http.c I see define of WS_RETKEY_SIZEM1, but below MAX_PATHLEN checked against WS_RETKEY_SIZE (raising compiler error about "WS_RETKEY_SIZE not defined").

Which is right?

**Comment by cnlohr** [comment]
What file is this in?  I am unfamiliar with this.

**Comment by king2** [comment]
/esp82xx/fwsrc/http.c.
I just realized that I created issue in wrong place, because it is related to esp82xx, not to colorchord itself. Sorry.

**Comment by cnlohr** [comment]
Yeah, I would say.  But to answer your question the WS stuff has to do with websockets.  I think it just matters that the PATHLEN is big enough that it doesn't overflow it when working with the key, so I am a little confused about what the problem would be.  Closing here, you can reopen at https://github.com/cnlohr/esp82xx
