### ISSUE TITLE
How do I get the Voronoi Diagram?

### ISSUE THREAD

**Issue by CubeyT** [cnlohr/colorchord#75]
Before I start, I am a newbie at coding. I know almost nothing, but I do know a bit about computers.

Anyways, I got the program working. I am using Windows 10 64 bit, but instead of the voronoi diagram in the back, I just have blue. How do I get the diagram to show up? Is it built in, or do I have to install it?

**Comment by cnlohr** [comment]
It should be built in.  Most of the time the biggest issues surround sound not getting into the program... Can you take a screen shot just in case I see something obvious.

Did you get terminal output associated with your program?

**Comment by CubeyT** [comment]
![colorchord screenshot](https://user-images.githubusercontent.com/44859825/48208303-239d8680-e338-11e8-8c08-54ea33b74784.PNG)
 Here's a screenshot of the program next to the terminal (I think that's what it's called)

Is there a hotkey to get it started? Another thing that could be important is that I used FireFlaker's .exe that was posted in the comments of another issue, but if I need to edit it, I don't know how to get there.

One thing that could be a problem is the "Warning: cannot open default.conf" but I really don't know what that means

**Comment by cnlohr** [comment]
"Warning cannot open default.conf" 

It needs to be run from the same folder as "default.conf"

**Comment by CubeyT** [comment]
Oh I see. It works perfectly now, thanks for the help 👍
