### ISSUE TITLE
APA102C support

### ISSUE THREAD

**Issue by geozukunft** [cnlohr/colorchord#94]
I couldn't find any information in the doc. Does colorchord support APA102C leds?

**Comment by cnlohr** [comment]
No, however, it would not be hard to hack support for it into your application.  What platform are you on?

**Comment by geozukunft** [comment]
I'm on ESP8266

**Comment by cnlohr** [comment]
I regret that there are no plans to support any synchronous serial LEDs on that platform it any time soon.  If you did it, I would be happy to accept a PR.  For now, though.... I am going to close the ticket.
