### ISSUE TITLE
Supporting direct audio input on STM32f407

### ISSUE THREAD

**Issue by r0n0x** [cnlohr/colorchord#95]
Hi, newcommer to C coding in general. I attempted to port the code for the F3 to the F4 because my F4, like many does not have an on-board microphone, also, even if it didnt, i still would rather use an audio-line in than use the microphone.

However eventually i ran into an issue, the adc.c cannot be used for the stm32f4 because the misc.c for the f4 does not exist. it is not an equivalent library so, simply changing refferences to the F3 misc library to the F4 will not work, and now i have no idea how to make my F4 read audio, short of manually re-making the adc.c for the stm32f4

Even if i had the F4 discovery, i would still not want to be reading audio from the microphone, but i also would not want to destroy the microphone and hard wire audio lines in.

Is there perhaps something im not seeing or some simple solution to read audio input from an stm32f407?

**Comment by cnlohr** [comment]
Did you abandon the project?
